import { AdminLayout } from '@/components/layout/AdminLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { router } from '@inertiajs/react';
import { Activity, CheckCircle2, CircleOff, RefreshCw, ShieldAlert, TimerReset } from 'lucide-react';
import { useState } from 'react';

type Check={id:number;service:string;providerKey:string;label:string;active:boolean;status:string;failures:number;threshold:number;cooldownMinutes:number;responseMs:number|null;error:string|null;checkedAt:string|null;successAt:string|null;circuitOpenUntil:string|null};
type Summary={healthy:number;attention:number;disabled:number;untested:number};
const colors:Record<string,string>={healthy:'bg-emerald-100 text-emerald-800',degraded:'bg-amber-100 text-amber-800',circuit_open:'bg-red-100 text-red-800',untested:'bg-slate-100 text-slate-700'};

export default function Health({checks,summary}:{checks:Check[];summary:Summary}){return <AdminLayout title="Integration Health"><div className="space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.16em] text-indigo-600">Operational resilience</p><h1 className="mt-2 text-2xl font-bold">Integration health</h1><p className="mt-1 text-gray-600">Monitor external services and pause repeated requests automatically when providers become unhealthy.</p></header><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<CheckCircle2/>} label="Healthy" value={summary.healthy} tone="text-emerald-700"/><Stat icon={<ShieldAlert/>} label="Needs attention" value={summary.attention} tone="text-amber-700"/><Stat icon={<CircleOff/>} label="Disabled" value={summary.disabled} tone="text-slate-600"/><Stat icon={<Activity/>} label="Not tested" value={summary.untested} tone="text-indigo-700"/></div><div className="grid gap-5 xl:grid-cols-2">{checks.map(check=><HealthCard key={check.id} check={check}/>)}</div>{!checks.length&&<div className="rounded-2xl border border-dashed bg-white p-12 text-center text-gray-500">No integrations have been configured for this property.</div>}</div></AdminLayout>}
function HealthCard({check}:{check:Check}){const[threshold,setThreshold]=useState(String(check.threshold));const[cooldown,setCooldown]=useState(String(check.cooldownMinutes));const update=(active=check.active)=>router.patch(route('dashboard.integration-health.update',check.id),{active,failure_threshold:Number(threshold),cooldown_minutes:Number(cooldown)},{preserveScroll:true});return <article className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-gray-400">{check.service}</p><h2 className="mt-1 text-lg font-semibold">{check.label}</h2><p className="mt-1 text-xs text-gray-500">Provider key: {check.providerKey}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold capitalize ${!check.active?'bg-slate-100 text-slate-600':colors[check.status]||colors.untested}`}>{check.active?check.status.replaceAll('_',' '):'disabled'}</span></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><Info label="Failures" value={`${check.failures} / ${check.threshold}`}/><Info label="Response" value={check.responseMs===null?'—':`${check.responseMs} ms`}/><Info label="Last checked" value={check.checkedAt?new Date(check.checkedAt).toLocaleString():'Never'}/><Info label="Last success" value={check.successAt?new Date(check.successAt).toLocaleString():'Never'}/></div>{check.circuitOpenUntil&&<div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-800">Requests paused until {new Date(check.circuitOpenUntil).toLocaleString()}.</div>}{check.error&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs text-amber-900">{check.error}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium text-gray-600">Failure threshold<Input className="mt-1" type="number" min="1" max="20" value={threshold} onChange={e=>setThreshold(e.target.value)}/></label><label className="text-xs font-medium text-gray-600">Cooldown (minutes)<Input className="mt-1" type="number" min="1" max="1440" value={cooldown} onChange={e=>setCooldown(e.target.value)}/></label></div><div className="mt-5 flex flex-wrap gap-2 border-t pt-4"><Button size="sm" onClick={()=>router.post(route('dashboard.integration-health.test',check.id),{},{preserveScroll:true})} disabled={!check.active}><RefreshCw className="mr-2" size={14}/>Test now</Button><Button size="sm" variant="outline" onClick={()=>update()}>Save protection</Button><Button size="sm" variant="outline" onClick={()=>update(!check.active)}>{check.active?'Disable':'Enable'}</Button>{check.status==='circuit_open'&&<Button size="sm" variant="outline" onClick={()=>router.post(route('dashboard.integration-health.reset',check.id),{},{preserveScroll:true})}><TimerReset className="mr-2" size={14}/>Restore</Button>}</div></article>}
function Stat({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:number;tone:string}){return <div className="flex items-center gap-4 rounded-2xl border bg-white p-5 shadow-sm"><span className={tone}>{icon}</span><div><p className="text-2xl font-bold">{value}</p><p className="text-xs text-gray-500">{label}</p></div></div>}
function Info({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 font-medium">{value}</p></div>}
