import { AdminLayout } from '@/components/layout/AdminLayout';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { router, useForm } from '@inertiajs/react';
import { FormEvent, useMemo, useState } from 'react';
import { Mail, RefreshCw, Send } from 'lucide-react';

type Settings={enabled:boolean;reply_to:string|null;due_days_before:number;overdue_repeat_days:number;invoice_subject:string;invoice_body:string;statement_subject:string;statement_body:string;deposit_subject:string;deposit_body:string;reminder_subject:string;reminder_body:string};
type Delivery={id:number;type:string;recipient:string;subject:string;status:string;attempts:number;scheduledFor:string|null;sentAt:string|null;openedAt:string|null;error:string|null};
type Invoice={id:number;number:string;recipient:string|null;account:string;balance:number};type Account={id:number;name:string;code:string;email:string};type Deposit={id:number;number:string;owner:string;recipient:string|null;amount:number};
const Field=({label,children}:{label:string;children:React.ReactNode})=><div className="space-y-2"><Label>{label}</Label>{children}</div>;
export default function Index({settings,deliveries,invoices,accounts,deposits}:{settings:Settings;deliveries:Delivery[];invoices:Invoice[];accounts:Account[];deposits:Deposit[]}){const[tab,setTab]=useState<'send'|'history'|'settings'>('send');const send=useForm({document_type:'invoice',document_id:'',recipient:'',subject:'',body:''});const config=useForm({...settings,reply_to:settings.reply_to||''});const docs=useMemo(()=>(send.data.document_type==='statement'?accounts:send.data.document_type==='deposit'?deposits:invoices) as (Invoice|Account|Deposit)[],[send.data.document_type,accounts,deposits,invoices]);const choose=(id:string)=>{const item=docs.find(x=>String(x.id)===id);const recipient=item&&'email'in item?item.email:item&&'recipient'in item?(item.recipient||''):'';send.setData({...send.data,document_id:id,recipient})};const submit=(e:FormEvent)=>{e.preventDefault();send.post(route('dashboard.communications.send'),{onSuccess:()=>setTab('history')})};return <AdminLayout title="Financial Emails"><div className="space-y-6"><header><h1 className="text-2xl font-bold">Financial communications</h1><p className="text-gray-600">Send branded financial documents and monitor queued email delivery.</p></header><div className="flex gap-2 rounded-xl bg-white p-2 shadow-sm">{(['send','history','settings'] as const).map(value=><Button key={value} variant={tab===value?'default':'ghost'} onClick={()=>setTab(value)} className="capitalize">{value}</Button>)}</div>
{tab==='send'&&<Card className="max-w-3xl"><CardHeader><CardTitle className="flex items-center gap-2"><Mail size={20}/>Send a financial document</CardTitle></CardHeader><CardContent><form className="space-y-5" onSubmit={submit}><div className="grid gap-4 sm:grid-cols-2"><Field label="Document type"><select className="w-full rounded-md border p-2" value={send.data.document_type} onChange={e=>send.setData({document_type:e.target.value,document_id:'',recipient:'',subject:'',body:''})}><option value="invoice">Invoice</option><option value="reminder">Payment reminder</option><option value="statement">Account statement</option><option value="deposit">Deposit receipt</option></select></Field><Field label="Document"><select required className="w-full rounded-md border p-2" value={send.data.document_id} onChange={e=>choose(e.target.value)}><option value="">Select document</option>{docs.map(item=><option key={item.id} value={item.id}>{'number'in item?item.number:`${(item as Account).name} (${(item as Account).code})`}</option>)}</select></Field></div><Field label="Recipient"><Input type="email" required value={send.data.recipient} onChange={e=>send.setData('recipient',e.target.value)}/></Field><Field label="Custom subject (optional)"><Input value={send.data.subject} onChange={e=>send.setData('subject',e.target.value)} placeholder="Uses the property template when blank"/></Field><Field label="Custom message (optional)"><Textarea rows={5} value={send.data.body} onChange={e=>send.setData('body',e.target.value)} placeholder="Uses the property template when blank"/></Field><p className="text-sm text-gray-500">A branded PDF is generated and attached automatically. Delivery runs through the notification queue.</p><Button disabled={send.processing}><Send className="mr-2" size={16}/>Queue email</Button></form></CardContent></Card>}
{tab==='history'&&<Card className="overflow-hidden"><CardHeader><CardTitle>Delivery history</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-gray-500"><tr>{['Document','Recipient','Status','Sent / opened','Attempts',''].map(h=><th key={h} className="px-5 py-3">{h}</th>)}</tr></thead><tbody className="divide-y">{deliveries.map(d=><tr key={d.id}><td className="px-5 py-4"><p className="font-medium">{d.subject}</p><p className="text-xs capitalize text-gray-500">{d.type}</p></td><td className="px-5 py-4">{d.recipient}</td><td className="px-5 py-4"><Badge variant={d.status==='failed'?'destructive':'secondary'}>{d.openedAt?'opened':d.status}</Badge>{d.error&&<p className="mt-1 max-w-xs truncate text-xs text-red-600" title={d.error}>{d.error}</p>}</td><td className="px-5 py-4 text-xs">{d.sentAt?new Date(d.sentAt).toLocaleString():'—'}{d.openedAt&&<><br/>Opened {new Date(d.openedAt).toLocaleString()}</>}</td><td className="px-5 py-4">{d.attempts}</td><td className="px-5 py-4">{d.status==='failed'&&<Button size="sm" variant="outline" onClick={()=>router.patch(route('dashboard.communications.retry',d.id))}><RefreshCw className="mr-2" size={14}/>Retry</Button>}</td></tr>)}{!deliveries.length&&<tr><td colSpan={6} className="p-10 text-center text-gray-500">No financial emails have been queued.</td></tr>}</tbody></table></div></CardContent></Card>}
{tab==='settings'&&<Card className="max-w-4xl"><CardHeader><CardTitle>Automation and templates</CardTitle></CardHeader><CardContent><form className="space-y-6" onSubmit={e=>{e.preventDefault();config.patch(route('dashboard.communications.settings'))}}><label className="flex items-center gap-3 rounded-lg border p-4"><input type="checkbox" checked={config.data.enabled} onChange={e=>config.setData('enabled',e.target.checked)}/><span><strong>Automated invoice reminders</strong><span className="block text-sm text-gray-500">The daily scheduler queues due and overdue reminders.</span></span></label><div className="grid gap-4 sm:grid-cols-3"><Field label="Reply-to email"><Input type="email" value={config.data.reply_to} onChange={e=>config.setData('reply_to',e.target.value)}/></Field><Field label="Reminder before due (days)"><Input type="number" min="0" max="30" value={config.data.due_days_before} onChange={e=>config.setData('due_days_before',Number(e.target.value))}/></Field><Field label="Repeat overdue every (days)"><Input type="number" min="1" max="90" value={config.data.overdue_repeat_days} onChange={e=>config.setData('overdue_repeat_days',Number(e.target.value))}/></Field></div>{(['invoice','statement','deposit','reminder'] as const).map(type=><div key={type} className="rounded-xl border p-5"><h3 className="mb-4 font-semibold capitalize">{type} template</h3><div className="space-y-4"><Field label="Subject"><Input value={config.data[`${type}_subject`]} onChange={e=>config.setData(`${type}_subject`,e.target.value)}/></Field><Field label="Message"><Textarea rows={4} value={config.data[`${type}_body`]} onChange={e=>config.setData(`${type}_body`,e.target.value)}/></Field></div></div>)}<p className="text-xs text-gray-500">Available placeholders: {'{{hotel}}'}, {'{{number}}'}, {'{{amount}}'}, {'{{balance}}'}, {'{{due_date}}'}.</p><Button disabled={config.processing}>Save communication settings</Button></form></CardContent></Card>}</div></AdminLayout>}
