<?php
namespace Tests\Feature;
use App\Models\{Guest,GuestServiceRequest,HousekeepingTask,Room,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Illuminate\Support\Str;use Tests\TestCase;
class GuestRequestCommunicationTest extends TestCase{use RefreshDatabase;private string$device='e84935dd-7610-43db-b928-e0838f299d78';
 public function test_guest_and_staff_can_converse_while_internal_notes_remain_private():void{[$guest,$token,$service]=$this->request();$manager=User::factory()->create(['role'=>'manager']);$this->auth($token)->postJson("/api/v1/requests/{$service->id}/messages",['message'=>'Please knock first.'])->assertCreated();$this->actingAs($manager)->post(route('dashboard.guest-requests.messages',$service),['message'=>'Worker will arrive shortly.','internal'=>false])->assertSessionHasNoErrors();$this->actingAs($manager)->post(route('dashboard.guest-requests.messages',$service),['message'=>'VIP handling note.','internal'=>true])->assertSessionHasNoErrors();auth()->forgetGuards();$response=$this->auth($token)->getJson("/api/v1/requests/{$service->id}")->assertOk()->assertJsonPath('data.messages.0.message','Please knock first.');$this->assertStringNotContainsString('VIP handling note.',json_encode($response->json()));$this->assertDatabaseHas('guest_request_events',['guest_service_request_id'=>$service->id,'event_type'=>'staff_replied']);}
 public function test_guest_can_attach_and_privately_view_a_request_image():void{Storage::fake('local');[$guest,$token,$service]=$this->request();$this->auth($token)->post("/api/v1/requests/{$service->id}/messages",['message'=>'This is the damaged item.','attachment'=>UploadedFile::fake()->image('damage.jpg')],['Accept'=>'application/json'])->assertCreated();$message=$service->messages()->firstOrFail();Storage::disk('local')->assertExists($message->attachment_path);$this->auth($token)->getJson("/api/v1/requests/{$service->id}")->assertOk()->assertJsonPath('data.messages.0.has_attachment',true);$this->auth($token)->get("/api/v1/requests/{$service->id}/messages/{$message->id}/attachment")->assertOk()->assertHeader('cache-control','no-store, private');}
 public function test_guest_can_cancel_before_work_but_not_after_it_starts():void{[$guest,$token,$service]=$this->request();$this->auth($token)->patchJson("/api/v1/requests/{$service->id}/cancel")->assertOk();$this->assertSame('cancelled',$service->fresh()->status);[, $token2,$second]=$this->request('102');$second->update(['status'=>'in_progress']);auth()->forgetGuards();$this->auth($token2)->patchJson("/api/v1/requests/{$second->id}/cancel")->assertStatus(422);}
 public function test_staff_completion_can_be_confirmed_or_reopened_by_guest():void{[$guest,$token,$service]=$this->request();$manager=User::factory()->create(['role'=>'manager']);$this->actingAs($manager)->post(route('dashboard.guest-requests.complete',$service),['completion_message'=>'Fresh towels delivered.'])->assertSessionHasNoErrors();$this->assertSame('completed',$service->fresh()->status);auth()->forgetGuards();$this->auth($token)->patchJson("/api/v1/requests/{$service->id}/resolution",['action'=>'reopen','message'=>'Only one towel arrived.'])->assertOk();$this->assertSame('pending',$service->fresh()->status);$service->update(['status'=>'completed']);$this->auth($token)->patchJson("/api/v1/requests/{$service->id}/resolution",['action'=>'confirm'])->assertOk();$this->assertSame('confirmed',$service->fresh()->status);$this->assertNotNull($service->fresh()->guest_confirmed_at);}
 private function request(string$number='101'):array{$guest=Guest::create(['first_name'=>'Mobile','last_name'=>'Guest','email'=>Str::random(5).'@example.com','password'=>'secret123']);$guest->devices()->create(['device_id'=>$this->device]);$token=$guest->createToken("guest-mobile:{$this->device}",['guest:mobile'],now()->addHour())->plainTextToken;$room=Room::create(['number'=>$number,'type'=>'Standard','status'=>'occupied']);$task=HousekeepingTask::create(['room_id'=>$room->id,'task_type'=>'service','status'=>'pending','priority'=>'normal']);$service=GuestServiceRequest::create(['guest_id'=>$guest->id,'room_id'=>$room->id,'type'=>'linen','status'=>'pending','priority'=>'normal','details'=>'Extra towels','housekeeping_task_id'=>$task->id]);$service->events()->create(['guest_id'=>$guest->id,'event_type'=>'created','label'=>'Guest created the request.','occurred_at'=>now()]);return[$guest,$token,$service];}private function auth(string$token):static{return$this->withToken($token)->withHeader('X-Device-ID',$this->device);}}
