<?php
namespace Tests\Feature;
use App\Models\{LockDevice,LockProviderConfig,LockSyncAttempt,Room,User};use App\Notifications\LockHealthAlert;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\{Http,Notification};use Tests\TestCase;
class LockProviderIntegrationTest extends TestCase{use RefreshDatabase;
 public function test_admin_can_configure_test_and_discover_provider():void{$admin=User::factory()->create(['role'=>'super_admin']);Http::fake(['https://locks.example.test/api/health'=>Http::response(['message'=>'Ready']),'https://locks.example.test/api/devices'=>Http::response(['devices'=>[['id'=>'vendor-1','name'=>'Lobby inventory','model'=>'X1','battery_level'=>88,'status'=>'online','capabilities'=>['rfid','mobile']]]])]);$this->actingAs($admin)->post(route('dashboard.locks.providers.store'),['name'=>'Example Locks','key'=>'example','driver'=>'generic_rest','base_url'=>'https://locks.example.test/api','token'=>'secret-token','webhook_secret'=>'1234567890abcdef','active'=>true])->assertSessionHasNoErrors();$provider=LockProviderConfig::first();$this->assertSame('secret-token',$provider->credentials['token']);$this->assertStringNotContainsString('secret-token',(string)\DB::table('lock_provider_configs')->value('credentials'));$this->actingAs($admin)->post(route('dashboard.locks.providers.test',$provider))->assertSessionHasNoErrors();$this->assertSame('connected',$provider->fresh()->connection_status);$this->actingAs($admin)->post(route('dashboard.locks.providers.discover',$provider))->assertSessionHas('discoveredLocks');}
 public function test_discovered_device_can_be_imported_and_synchronized():void{$admin=User::factory()->create(['role'=>'super_admin']);LockProviderConfig::create(['name'=>'Example','key'=>'example','driver'=>'generic_rest','base_url'=>'https://locks.example.test/api','credentials'=>['token'=>'abc'],'active'=>true]);$this->actingAs($admin)->post(route('dashboard.locks.import'),['devices'=>[['provider'=>'example','external_id'=>'vendor-2','name'=>'Room inventory','hardware_model'=>'X2','firmware_version'=>'2.1','battery_level'=>72,'status'=>'online','capabilities'=>['rfid','mobile']]]])->assertSessionHasNoErrors();$device=LockDevice::first();Http::fake(['https://locks.example.test/api/devices/vendor-2'=>Http::response(['status'=>'online','battery_level'=>70,'firmware_version'=>'2.2','hardware_model'=>'X2','capabilities'=>['rfid','mobile']])]);$this->actingAs($admin)->post(route('dashboard.locks.sync',$device))->assertSessionHasNoErrors();$this->assertSame('synced',$device->fresh()->sync_status);$this->assertSame('2.2',$device->fresh()->firmware_version);$this->assertDatabaseHas('lock_sync_attempts',['lock_device_id'=>$device->id,'status'=>'completed']);}
 public function test_signed_webhook_updates_lock_and_notifies_managers():void{Notification::fake();$manager=User::factory()->create(['role'=>'manager','status'=>'active']);$provider=LockProviderConfig::create(['name'=>'Example','key'=>'example','driver'=>'generic_rest','base_url'=>'https://locks.example.test/api','webhook_secret'=>'1234567890abcdef','active'=>true]);$room=Room::create(['number'=>'901','type'=>'Suite','floor'=>9,'status'=>'available','price'=>300]);$device=LockDevice::create(['room_id'=>$room->id,'provider'=>'example','external_id'=>'vendor-901','name'=>'Room 901 Lock','status'=>'online','battery_level'=>90]);$payload=['id'=>'evt-1','type'=>'low_battery','device_id'=>'vendor-901','battery_level'=>18,'status'=>'online'];$json=json_encode($payload);$response=$this->call('POST',route('webhooks.locks',['providerKey'=>'example']),[],[],[],['CONTENT_TYPE'=>'application/json','HTTP_X_LOCK_SIGNATURE'=>hash_hmac('sha256',$json,$provider->webhook_secret)],$json);$response->assertOk();$this->assertSame(18,$device->fresh()->battery_level);$this->assertDatabaseHas('room_events',['room_id'=>$room->id,'event_type'=>'lock_low_battery']);Notification::assertSentTo($manager,LockHealthAlert::class);}
 public function test_emergency_fallback_requires_reason_and_is_audited():void{$admin=User::factory()->create(['role'=>'super_admin']);$room=Room::create(['number'=>'902','type'=>'Suite','floor'=>9,'status'=>'available','price'=>300]);$device=LockDevice::create(['room_id'=>$room->id,'provider'=>'simulator','external_id'=>'sim-902','name'=>'Room 902 Lock','status'=>'offline','battery_level'=>10]);$this->actingAs($admin)->post(route('dashboard.locks.emergency',$device),['reason'=>'Guest welfare emergency'])->assertSessionHasNoErrors();$this->assertDatabaseHas('lock_commands',['lock_device_id'=>$device->id,'command'=>'manual_emergency_override','status'=>'pending_manual']);$this->assertDatabaseHas('audit_events',['action'=>'emergency_access_requested','severity'=>'critical']);}
}
