<?php
namespace Tests\Feature;
use App\Models\{Hotel,HotelSubscription,Plan,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Http\UploadedFile;use Illuminate\Support\Facades\Storage;use Tests\TestCase;
class PropertyBrandingTest extends TestCase{use RefreshDatabase;
private function payload():array{return['display_name'=>'Ocean Key Resort','primary_color'=>'#123456','accent_color'=>'#FEDCBA','support_email'=>'support@ocean.test','support_phone'=>'876-555-0110','email_sender_name'=>'Ocean Key','welcome_message'=>'Welcome to the coast.','id_requirement'=>'optional','terms'=>'Guest terms.','privacy_policy'=>'Privacy terms.','checkin_message'=>'Your room is ready.','checkout_message'=>'Thank you for staying.','request_update_message'=>'Your request was updated.'];}
public function test_hotel_super_admin_can_update_branding_and_logo():void{Storage::fake('public');$admin=User::factory()->create(['role'=>'super_admin']);$payload=$this->payload()+['logo'=>UploadedFile::fake()->image('logo.png',300,150)];$this->actingAs($admin)->post(route('dashboard.settings.property'),$payload)->assertSessionHasNoErrors();$hotel=$admin->hotel->fresh();$this->assertSame('Ocean Key Resort',$hotel->settings['branding']['display_name']);Storage::disk('public')->assertExists($hotel->settings['logo_path']);}
public function test_non_super_admin_cannot_update_property_identity():void{$manager=User::factory()->create(['role'=>'manager']);$this->actingAs($manager)->post(route('dashboard.settings.property'),$this->payload())->assertForbidden();}
public function test_public_property_endpoint_is_tenant_specific_and_safe():void{$hotel=Hotel::create(['name'=>'Island Hotel','slug'=>'island-hotel','status'=>'active','timezone'=>'America/Jamaica','currency'=>'JMD','settings'=>['branding'=>$this->payload()]]);HotelSubscription::create(['hotel_id'=>$hotel->id,'plan_id'=>Plan::where('key','core')->firstOrFail()->id,'status'=>'active']);$response=$this->withHeader('X-Hotel-Slug','island-hotel')->getJson('/api/v1/property')->assertOk();$response->assertJsonPath('data.name','Ocean Key Resort')->assertJsonPath('data.primary_color','#123456')->assertJsonMissingPath('data.checkin_message')->assertJsonMissingPath('data.email_sender_name');}
public function test_platform_admin_can_update_client_branding():void{$platform=User::factory()->create(['is_platform_admin'=>true]);$hotel=Hotel::create(['name'=>'Client Hotel','slug'=>'client-hotel','status'=>'active','timezone'=>'America/Jamaica','currency'=>'JMD']);$this->actingAs($platform)->post(route('platform.hotels.onboarding.branding',$hotel),$this->payload())->assertSessionHasNoErrors();$this->assertSame('#123456',$hotel->fresh()->settings['branding']['primary_color']);}}
