<?php
namespace Tests\Feature;
use App\Models\{Checkin,Guest,HousekeepingTask,Reservation,ReservationEvent,Room,StayDeparture,User};use Illuminate\Foundation\Testing\RefreshDatabase;use Inertia\Testing\AssertableInertia as Assert;use Tests\TestCase;
class ReservationLifecycleTest extends TestCase{use RefreshDatabase;private function base(bool$active=false):array{$admin=User::factory()->create(['role'=>'manager']);$guest=Guest::create(['first_name'=>'Life','last_name'=>'Cycle','id_status'=>'verified']);$room=Room::create(['number'=>'801','type'=>'Suite','status'=>$active?'occupied':'available','price'=>200]);$r=Reservation::create(['guest_id'=>$guest->id,'room_id'=>$room->id,'reference'=>'RS-LIFECYCLE','arrival_date'=>today(),'departure_date'=>today()->addDays(3),'guest_count'=>2,'room_type'=>'Suite','status'=>$active?'checked_in':'confirmed','payment_status'=>'paid','total_amount'=>600,'amount_paid'=>600,'source'=>'direct']);$c=$active?Checkin::create(['reservation_id'=>$r->id,'guest_id'=>$guest->id,'room_id'=>$room->id,'check_in_date'=>today(),'check_out_date'=>today()->addDays(3),'booking_reference'=>$r->reference,'is_active'=>true]):null;return[$admin,$guest,$room,$r,$c];}
 public function test_reservation_workspace_can_be_opened_and_edited():void{[$a,,,$r]=$this->base();$this->actingAs($a)->get(route('dashboard.bookings.show',$r))->assertOk()->assertInertia(fn(Assert$p)=>$p->component('Bookings/Detail')->where('reservation.reference','RS-LIFECYCLE'));$this->actingAs($a)->patch(route('dashboard.bookings.update',$r),['room_id'=>$r->room_id,'arrival_date'=>today()->addDay()->toDateString(),'departure_date'=>today()->addDays(5)->toDateString(),'guest_count'=>3,'room_type'=>'Suite','payment_status'=>'paid','total_amount'=>800,'amount_paid'=>600,'source'=>'phone','group_code'=>'WEDDING','special_requests'=>'Cot'])->assertSessionHasNoErrors();$this->assertSame(3,$r->fresh()->guest_count);$this->assertDatabaseHas('reservation_events',['reservation_id'=>$r->id,'type'=>'reservation_updated']);}
 public function test_no_show_releases_inventory_and_records_fee():void{[$a,,,$r]=$this->base();$this->actingAs($a)->patch(route('dashboard.bookings.no-show',$r),['fee'=>150,'reason'=>'Guest did not arrive'])->assertSessionHasNoErrors();$this->assertSame('no_show',$r->fresh()->status);$this->assertSame('150.00',$r->fresh()->no_show_fee);$this->assertNotNull($r->fresh()->no_show_at);}
 public function test_active_stay_can_be_extended_and_transferred():void{[$a,$g,$old,$r,$c]=$this->base(true);$this->actingAs($a)->patch(route('dashboard.bookings.stay-dates',$r),['departure_date'=>today()->addDays(5)->toDateString(),'reason'=>'Guest extended'])->assertSessionHasNoErrors();$this->assertSame(today()->addDays(5)->toDateString(),$c->fresh()->check_out_date->toDateString());$new=Room::create(['number'=>'802','type'=>'Deluxe','status'=>'available','price'=>250]);$this->actingAs($a)->patch(route('dashboard.bookings.transfer',$r),['room_id'=>$new->id,'reason'=>'Air conditioning issue'])->assertSessionHasNoErrors();$this->assertSame($new->id,$c->fresh()->room_id);$this->assertSame('cleaning',$old->fresh()->status);$this->assertSame('occupied',$new->fresh()->status);$this->assertDatabaseHas('housekeeping_tasks',['room_id'=>$old->id,'checkin_id'=>$c->id]);$this->assertDatabaseHas('reservation_events',['reservation_id'=>$r->id,'type'=>'room_transferred']);}
 public function test_manager_can_review_departure_and_release_restriction():void{[$a,$g,$room,$r,$c]=$this->base(true);$g->update(['do_not_rent_at'=>now(),'do_not_rent_reason'=>'Incident']);$d=StayDeparture::create(['checkin_id'=>$c->id,'reservation_id'=>$r->id,'guest_id'=>$g->id,'room_id'=>$room->id,'type'=>'early','financial_resolution'=>'pending','departed_at'=>now(),'performed_by'=>$a->id]);$this->actingAs($a)->patch(route('dashboard.departures.review',$d),['financial_resolution'=>'partial_refund','refund_amount'=>100,'notes'=>'Approved by manager'])->assertSessionHasNoErrors();$this->assertNotNull($d->fresh()->financial_reviewed_at);$this->assertSame('Approved by manager',$d->fresh()->financial_review_notes);$this->actingAs($a)->patch(route('dashboard.guests.release-restriction',$g),['reason'=>'Management review completed'])->assertSessionHasNoErrors();$this->assertNull($g->fresh()->do_not_rent_at);}
}
