<?php
namespace Tests\Feature;
use App\Models\{AuditEvent,LockDevice,Room,User};use App\Notifications\AdminTwoFactorCode;use Illuminate\Foundation\Testing\RefreshDatabase;use Illuminate\Support\Facades\Notification;use Tests\TestCase;
class SecurityAuditTest extends TestCase{use RefreshDatabase;
 public function test_failed_and_successful_logins_are_audited():void{$user=User::factory()->create();$this->post('/login',['email'=>$user->email,'password'=>'wrong']);$this->assertDatabaseHas('audit_events',['action'=>'login_failed','severity'=>'warning']);$this->post('/login',['email'=>$user->email,'password'=>'password']);$this->assertDatabaseHas('audit_events',['action'=>'login_succeeded','actor_id'=>$user->id]);}
 public function test_remote_unlock_requires_reason_and_is_audited():void{$admin=User::factory()->create(['role'=>'super_admin']);$room=Room::create(['number'=>'701','type'=>'Suite','floor'=>7,'status'=>'available','price'=>200]);$lock=LockDevice::create(['room_id'=>$room->id,'provider'=>'simulator','external_id'=>'security-701','name'=>'Security Lock','status'=>'online','battery_level'=>100]);$this->actingAs($admin)->post(route('dashboard.locks.unlock',$lock),[])->assertSessionHasErrors('reason');$this->actingAs($admin)->post(route('dashboard.locks.unlock',$lock),['reason'=>'Emergency welfare check'])->assertSessionHasNoErrors();$this->assertDatabaseHas('audit_events',['action'=>'remote_unlock','reason'=>'Emergency welfare check','severity'=>'critical']);}
 public function test_only_super_admin_can_view_security_center():void{$admin=User::factory()->create(['role'=>'super_admin']);$manager=User::factory()->create(['role'=>'manager']);$this->actingAs($admin)->get(route('dashboard.security.index'))->assertOk();$this->actingAs($manager)->get(route('dashboard.security.index'))->assertForbidden();}
 public function test_enabled_admin_two_factor_sends_code_and_stops_initial_login():void{Notification::fake();$admin=User::factory()->create(['role'=>'super_admin','two_factor_enabled'=>true]);$response=$this->post('/login',['email'=>$admin->email,'password'=>'password']);$this->assertGuest();$response->assertRedirect(route('two-factor.challenge'));Notification::assertSentTo($admin,AdminTwoFactorCode::class);$this->assertNotNull($admin->fresh()->two_factor_code_hash);}
}
