<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\{FoodCategory,FoodItem,FoodOrder};use Illuminate\Http\{JsonResponse,Request};use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class GuestFoodOrderController extends Controller{
 public function menu():JsonResponse{return response()->json(['data'=>FoodCategory::where('active',true)->with(['items'=>fn($q)=>$q->where('available',true)->orderBy('name')])->orderBy('sort_order')->get()->map(fn($c)=>['id'=>$c->id,'name'=>$c->name,'items'=>$c->items->map(fn($i)=>['id'=>$i->id,'name'=>$i->name,'description'=>$i->description,'price'=>(float)$i->price,'tax_rate'=>(float)$i->tax_rate,'dietary_tags'=>$i->dietary_tags??[],'allergens'=>$i->allergens])])]);}
 public function index(Request$r):JsonResponse{return response()->json(['data'=>FoodOrder::where('guest_id',$r->user()->id)->with('items')->latest()->limit(50)->get()]);}
 public function store(Request$r):JsonResponse{$v=$r->validate(['items'=>'required|array|min:1|max:30','items.*.id'=>'required|integer|exists:food_items,id','items.*.quantity'=>'required|integer|between:1,20','items.*.modifiers'=>'nullable|string|max:500','notes'=>'nullable|string|max:1000','payment_method'=>'required|in:room_charge,pay_on_delivery']);$stay=$r->user()->checkins()->where('is_active',true)->with('room')->latest()->first();abort_unless($stay,422,'An active stay is required to place a food order.');$items=FoodItem::whereIn('id',collect($v['items'])->pluck('id'))->where('available',true)->get()->keyBy('id');abort_unless($items->count()===collect($v['items'])->pluck('id')->unique()->count(),422,'One or more menu items are unavailable.');$order=DB::transaction(function()use($r,$v,$stay,$items){$subtotal=0;$tax=0;$lines=[];foreach($v['items']as$line){$item=$items[$line['id']];$base=round((float)$item->price*$line['quantity'],2);$lineTax=round($base*(float)$item->tax_rate/100,2);$subtotal+=$base;$tax+=$lineTax;$lines[]=['food_item_id'=>$item->id,'name'=>$item->name,'quantity'=>$line['quantity'],'unit_price'=>$item->price,'tax_amount'=>$lineTax,'total'=>$base+$lineTax,'modifiers'=>$line['modifiers']??null];}$order=FoodOrder::create(['guest_id'=>$r->user()->id,'checkin_id'=>$stay->id,'room_id'=>$stay->room_id,'number'=>'FB-'.now()->format('ymd').'-'.strtoupper(Str::random(5)),'payment_method'=>$v['payment_method'],'subtotal'=>$subtotal,'tax_total'=>$tax,'total'=>$subtotal+$tax,'notes'=>$v['notes']??null]);foreach($lines as$line)$order->items()->create($line);return$order;});return response()->json(['data'=>$order->load('items')],201);}
 public function cancel(Request$r,FoodOrder$order):JsonResponse{abort_unless($order->guest_id===$r->user()->id,404);abort_unless(in_array($order->status,['new','accepted']),422,'This order can no longer be cancelled in the app.');$order->update(['status'=>'cancelled','cancelled_at'=>now()]);return response()->json(['message'=>'Order cancelled.']);}
}
