<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller;use App\Models\{GuestRequestEvent,GuestRequestMessage,GuestServiceRequest,RoomEvent};use App\Services\Security\AuditLogger;use Illuminate\Http\{JsonResponse,Request};use Illuminate\Support\Facades\Storage;
class GuestRequestController extends Controller{
 public function show(Request$request,GuestServiceRequest$serviceRequest):JsonResponse{$this->own($request,$serviceRequest);$serviceRequest->messages()->whereNull('guest_id')->where('internal',false)->whereNull('read_by_guest_at')->update(['read_by_guest_at'=>now()]);$serviceRequest->load(['messages'=>fn($q)=>$q->where('internal',false)->with('user:id,name')->oldest(),'events'=>fn($q)=>$q->oldest(),'room:id,number']);return response()->json(['data'=>['request'=>$serviceRequest->only(['id','type','status','priority','details','completed_at','guest_confirmed_at','cancelled_at'])+['room'=>$serviceRequest->room,'has_completion_photo'=>(bool)$serviceRequest->completion_photo],'messages'=>$serviceRequest->messages->map(fn($m)=>['id'=>$m->id,'sender'=>$m->guest_id?'guest':($m->user?->name??'staff'),'message'=>$m->message,'has_attachment'=>(bool)$m->attachment_path,'created_at'=>$m->created_at?->toISOString()]),'timeline'=>$serviceRequest->events->map(fn($e)=>['type'=>$e->event_type,'label'=>$e->label,'occurred_at'=>$e->occurred_at?->toISOString()])]]);}
 public function message(Request$request,GuestServiceRequest$serviceRequest):JsonResponse{$this->own($request,$serviceRequest);abort_if(in_array($serviceRequest->status,['cancelled','confirmed']),422,'This request is closed.');$data=$request->validate(['message'=>'required|string|max:2000','attachment'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120']);$path=$request->file('attachment')?->store("guest-request-attachments/{$serviceRequest->id}",'local');$message=$serviceRequest->messages()->create(['guest_id'=>$request->user()->id,'message'=>$data['message'],'attachment_path'=>$path,'read_by_guest_at'=>now()]);$this->event($serviceRequest,'guest_replied','Guest sent a message.',$request->user()->id);return response()->json(['data'=>$message],201);}
 public function cancel(Request$request,GuestServiceRequest$serviceRequest):JsonResponse{$this->own($request,$serviceRequest);abort_unless(in_array($serviceRequest->status,['pending','assigned']),422,'A request cannot be cancelled after work begins.');$serviceRequest->update(['status'=>'cancelled','cancelled_at'=>now()]);$serviceRequest->housekeepingTask?->update(['status'=>'cancelled']);$serviceRequest->maintenanceWorkOrder?->update(['status'=>'cancelled']);$this->event($serviceRequest,'cancelled','Guest cancelled the request.',$request->user()->id);RoomEvent::create(['room_id'=>$serviceRequest->room_id,'guest_id'=>$serviceRequest->guest_id,'checkin_id'=>$serviceRequest->checkin_id,'event_type'=>'guest_service_cancelled','description'=>'Guest cancelled a service request before work began.','occurred_at'=>now()]);AuditLogger::actor(null,'guest_service_cancelled','operations','standard','Guest cancelled a service request.',$serviceRequest);return response()->json(['message'=>'Request cancelled.']);}
 public function resolution(Request$request,GuestServiceRequest$serviceRequest):JsonResponse{$this->own($request,$serviceRequest);$action=$request->validate(['action'=>'required|in:confirm,reopen','message'=>'nullable|string|max:2000'])['action'];abort_unless($serviceRequest->status==='completed',422,'Only completed requests can be confirmed or reopened.');if($action==='confirm'){$serviceRequest->update(['status'=>'confirmed','guest_confirmed_at'=>now()]);$this->event($serviceRequest,'guest_confirmed','Guest confirmed the request was resolved.',$request->user()->id);}else{$serviceRequest->update(['status'=>'pending','completed_at'=>null,'guest_confirmed_at'=>null]);$serviceRequest->housekeepingTask?->update(['status'=>'pending','completed_at'=>null]);$serviceRequest->maintenanceWorkOrder?->update(['status'=>'open','repaired_at'=>null]);$this->event($serviceRequest,'reopened','Guest reported that the request still needs attention.',$request->user()->id);if(filled($request->input('message')))$serviceRequest->messages()->create(['guest_id'=>$request->user()->id,'message'=>$request->input('message'),'read_by_guest_at'=>now()]);}return response()->json(['message'=>$action==='confirm'?'Resolution confirmed.':'Request reopened.']);}
 public function photo(Request$request,GuestServiceRequest$serviceRequest){$this->own($request,$serviceRequest);abort_unless($serviceRequest->completion_photo&&Storage::disk('local')->exists($serviceRequest->completion_photo),404);return Storage::disk('local')->response($serviceRequest->completion_photo,null,['Cache-Control'=>'no-store, private']);}
 public function attachment(Request$request,GuestServiceRequest$serviceRequest,GuestRequestMessage$message){$this->own($request,$serviceRequest);abort_unless($message->guest_service_request_id===$serviceRequest->id&&!$message->internal&&$message->attachment_path&&Storage::disk('local')->exists($message->attachment_path),404);return Storage::disk('local')->response($message->attachment_path,null,['Cache-Control'=>'no-store, private']);}
 private function own(Request$request,GuestServiceRequest$serviceRequest):void{abort_unless($serviceRequest->guest_id===$request->user()->id,404);}private function event(GuestServiceRequest$r,string$type,string$label,?int$guestId=null):void{GuestRequestEvent::create(['guest_service_request_id'=>$r->id,'guest_id'=>$guestId,'event_type'=>$type,'label'=>$label,'occurred_at'=>now()]);}
}
