import { PlatformLayout } from '@/components/layout/PlatformLayout';
import { Link, router, useForm } from '@inertiajs/react';
import { Bed, Building2, CircleCheck, CirclePause, Eye, KeyRound, Layers3, Plus, Search, Settings2, UserRound, Users, X } from 'lucide-react';
import { FormEvent, ReactNode, useState } from 'react';

type Plan = { id:number; key:string; name:string; limits:{rooms:number|null;staff:number|null}; features:string[] };
type Feature = { key:string; name:string; enabled:boolean; override:boolean|null };
type Hotel = { id:number; name:string; slug:string; status:string; timezone:string; currency:string; planId:number|null; plan:string|null; subscriptionStatus:string; subscriptionState:string; trialStartedAt:string|null; trialEndsAt:string|null; graceEndsAt:string|null; features:Feature[]; usage:{rooms:number;staff:number;guests:number;locks:number}; limits:{rooms:number|null;staff:number|null}; admin:{id:number;name:string;email:string;status:string}|null;superAdmins:{id:number;name:string;email:string;status:string}[];recoveryCandidates:{id:number;name:string;email:string;role:string}[];createdAt:string };

export default function Hotels({ hotels, plans }: { hotels:Hotel[]; plans:Plan[] }) {
    const [creating, setCreating] = useState(false);
    const [editing, setEditing] = useState<Hotel|null>(null);
    const [recovering, setRecovering] = useState<Hotel|null>(null);
    const [query, setQuery] = useState('');
    const create = useForm({ name:'', slug:'', timezone:'America/Jamaica', currency:'JMD', plan_id:String(plans[0]?.id ?? ''), subscription_mode:'trial', trial_days:'14', admin_first_name:'', admin_last_name:'', admin_email:'', admin_password:'', admin_password_confirmation:'' });
    const visible = hotels.filter(hotel => `${hotel.name} ${hotel.slug} ${hotel.admin?.email ?? ''}`.toLowerCase().includes(query.toLowerCase()));
    const active = hotels.filter(hotel => hotel.status === 'active').length;
    const rooms = hotels.reduce((total, hotel) => total + hotel.usage.rooms, 0);
    const staff = hotels.reduce((total, hotel) => total + hotel.usage.staff, 0);

    const submit = (event:FormEvent) => {
        event.preventDefault();
        create.post(route('platform.hotels.store'), { onSuccess: () => { setCreating(false); create.reset(); } });
    };

    return <PlatformLayout>
        <section className="mb-8 overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950 px-6 py-7 text-white shadow-xl shadow-slate-900/10 lg:px-8">
            <div className="flex flex-wrap items-center justify-between gap-5">
                <div><p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-amber-400">SaaS control center</p><h1 className="text-3xl font-bold tracking-tight lg:text-4xl">Client hotels</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Manage properties, subscriptions, module access, account limits, and secure support sessions from one place.</p></div>
                <button onClick={() => setCreating(true)} className="flex items-center gap-2 rounded-xl bg-amber-400 px-5 py-3 text-sm font-bold text-slate-950 shadow-lg transition hover:bg-amber-300"><Plus size={18}/>Add client hotel</button>
            </div>
        </section>

        <section className="mb-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
            <Summary icon={<Building2/>} label="Total properties" value={hotels.length} tone="indigo"/>
            <Summary icon={<CircleCheck/>} label="Active properties" value={active} tone="green"/>
            <Summary icon={<Bed/>} label="Rooms managed" value={rooms} tone="amber"/>
            <Summary icon={<Users/>} label="Staff accounts" value={staff} tone="blue"/>
        </section>

        <div className="mb-5 flex flex-wrap items-end justify-between gap-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5">
            <div><h2 className="text-xl font-bold">Property directory</h2><p className="mt-1 text-sm text-slate-500">Showing {visible.length} of {hotels.length} properties</p></div>
            <label className="relative block w-full sm:w-80"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search hotels or administrators" className="w-full rounded-xl border border-slate-200 bg-white py-2.5 pl-10 pr-4 text-sm shadow-sm outline-none transition focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100"/></label>
        </div>

        <div className="grid gap-5 xl:grid-cols-2">
            {visible.map(hotel => <HotelCard key={hotel.id} hotel={hotel} onManage={() => setEditing(hotel)} onRecover={()=>setRecovering(hotel)}/>)}
            {visible.length === 0 && <div className="col-span-full rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-16 text-center"><Search className="mx-auto text-slate-300" size={36}/><h3 className="mt-4 font-bold">No properties found</h3><p className="mt-1 text-sm text-slate-500">Try a different name, slug, or administrator email.</p></div>}
        </div>

        {creating && <Modal title="Add client hotel" subtitle="Create the property, subscription, and its first administrator." close={() => setCreating(false)}>
            <form onSubmit={submit} className="space-y-6">
                <FormSection title="Property details"><div className="grid gap-4 sm:grid-cols-2"><Field label="Hotel name" error={create.errors.name}><input value={create.data.name} onChange={e => create.setData('name',e.target.value)} onBlur={() => !create.data.slug && create.setData('slug',create.data.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,''))} required/></Field><Field label="Property slug" error={create.errors.slug}><input value={create.data.slug} onChange={e => create.setData('slug',e.target.value)} required/></Field><Field label="Timezone" error={create.errors.timezone}><input value={create.data.timezone} onChange={e => create.setData('timezone',e.target.value)} required/></Field><Field label="Currency" error={create.errors.currency}><input maxLength={3} value={create.data.currency} onChange={e => create.setData('currency',e.target.value.toUpperCase())} required/></Field><Field label="Subscription plan" error={create.errors.plan_id}><select value={create.data.plan_id} onChange={e => create.setData('plan_id',e.target.value)}>{plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></Field><Field label="Access type" error={create.errors.subscription_mode}><select value={create.data.subscription_mode} onChange={e=>create.setData('subscription_mode',e.target.value)}><option value="trial">Free trial</option><option value="active">Active subscription</option></select></Field>{create.data.subscription_mode==='trial'&&<Field label="Trial length (days)" error={create.errors.trial_days}><input type="number" min={1} max={90} value={create.data.trial_days} onChange={e=>create.setData('trial_days',e.target.value)}/></Field>}</div></FormSection>
                <FormSection title="First administrator"><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" error={create.errors.admin_first_name}><input value={create.data.admin_first_name} onChange={e => create.setData('admin_first_name',e.target.value)} required/></Field><Field label="Last name" error={create.errors.admin_last_name}><input value={create.data.admin_last_name} onChange={e => create.setData('admin_last_name',e.target.value)} required/></Field><Field label="Email address" error={create.errors.admin_email}><input type="email" value={create.data.admin_email} onChange={e => create.setData('admin_email',e.target.value)} required/></Field><div/><Field label="Temporary password" error={create.errors.admin_password}><input type="password" value={create.data.admin_password} onChange={e => create.setData('admin_password',e.target.value)} required/></Field><Field label="Confirm password"><input type="password" value={create.data.admin_password_confirmation} onChange={e => create.setData('admin_password_confirmation',e.target.value)} required/></Field></div></FormSection>
                <ModalActions close={() => setCreating(false)} processing={create.processing} label="Create hotel"/>
            </form>
        </Modal>}
        {editing && <ManageHotel hotel={editing} plans={plans} close={() => setEditing(null)}/>} 
        {recovering&&<RecoveryModal hotel={recovering} close={()=>setRecovering(null)}/>} 
    </PlatformLayout>;
}

function HotelCard({ hotel, onManage,onRecover }: { hotel:Hotel; onManage:()=>void;onRecover:()=>void }) {
    const enabled = hotel.features.filter(feature => feature.enabled);
    return <article className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg">
        <div className="border-b border-slate-100 p-5 lg:p-6"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-xl bg-indigo-50 p-3 text-indigo-700"><Building2 size={22}/></div><div><h2 className="text-lg font-bold text-slate-900">{hotel.name}</h2><p className="mt-0.5 text-xs font-medium text-slate-500">/{hotel.slug}</p></div></div><Status status={hotel.status}/></div></div>
        <div className="p-5 lg:p-6">
            <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Metric icon={<Bed size={17}/>} label="Rooms" value={`${hotel.usage.rooms}${hotel.limits.rooms !== null ? ` / ${hotel.limits.rooms}` : ''}`}/><Metric icon={<Users size={17}/>} label="Staff" value={`${hotel.usage.staff}${hotel.limits.staff !== null ? ` / ${hotel.limits.staff}` : ''}`}/><Metric icon={<UserRound size={17}/>} label="Guests" value={hotel.usage.guests}/><Metric icon={<KeyRound size={17}/>} label="Locks" value={hotel.usage.locks}/></div>
            <div className="mt-5 grid gap-3 rounded-xl border border-slate-100 bg-slate-50/80 p-4 sm:grid-cols-2"><div><p className="flex items-center gap-1.5 text-xs font-medium uppercase tracking-wide text-slate-400"><Layers3 size={13}/>Subscription</p><p className="mt-1 font-bold text-slate-800">{hotel.plan ?? 'No plan'} <span className="ml-1 text-xs font-medium capitalize text-slate-500">· {hotel.subscriptionState}</span></p>{hotel.trialEndsAt&&<p className="mt-1 text-xs text-slate-500">Trial ends {new Date(hotel.trialEndsAt).toLocaleDateString()}</p>}</div><div className="sm:text-right"><p className="text-xs font-medium uppercase tracking-wide text-slate-400">Primary administrator</p><p className="mt-1 truncate text-sm font-semibold text-slate-700">{hotel.admin?.email ?? 'Not assigned'}</p></div></div>
            <div className="mt-5"><p className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-400">Enabled modules</p><div className="flex flex-wrap gap-2">{enabled.map(feature => <span key={feature.key} className="rounded-md bg-indigo-50 px-2.5 py-1 text-xs font-medium text-indigo-700">{feature.name}{feature.override !== null ? ' *' : ''}</span>)}{enabled.length === 0 && <span className="text-sm text-slate-400">No modules enabled</span>}</div></div>
            <div className="mt-6 flex flex-wrap justify-end gap-2 border-t border-slate-100 pt-5"><button onClick={onRecover} className="flex items-center gap-2 rounded-lg border border-red-200 bg-red-50 px-3.5 py-2.5 text-sm font-semibold text-red-700"><KeyRound size={16}/>Admin recovery</button><Link href={route('platform.hotels.onboarding',hotel.id)} className="flex items-center gap-2 rounded-lg border border-indigo-200 bg-indigo-50 px-3.5 py-2.5 text-sm font-semibold text-indigo-700 transition hover:bg-indigo-100"><CircleCheck size={16}/>Onboarding</Link><button onClick={() => confirm(`Enter ${hotel.name} as its administrator?`) && router.post(route('platform.hotels.impersonate',hotel.id))} className="flex items-center gap-2 rounded-lg border border-slate-200 px-3.5 py-2.5 text-sm font-semibold text-slate-700 transition hover:bg-slate-50"><Eye size={16}/>Support view</button><button onClick={onManage} className="flex items-center gap-2 rounded-lg bg-indigo-700 px-3.5 py-2.5 text-sm font-semibold text-white transition hover:bg-indigo-800"><Settings2 size={16}/>Manage hotel</button></div>
        </div>
    </article>;
}

function RecoveryModal({hotel,close}:{hotel:Hotel;close:()=>void}){const form=useForm({compromised_user_id:String(hotel.superAdmins.find(a=>a.status==='active')?.id??''),replacement_user_id:'',first_name:'',last_name:'',email:'',password:'',password_confirmation:'',platform_password:'',incident_reason:'',confirmation:''});return <Modal title={`Recover ${hotel.name} administrator`} subtitle="Emergency account-compromise response" close={close}><form onSubmit={e=>{e.preventDefault();form.post(route('platform.hotels.admin-recovery',hotel.id),{onSuccess:close})}} className="space-y-5"><div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">The compromised account will be suspended and all known sessions and API tokens revoked immediately.</div><Field label="Compromised administrator"><select value={form.data.compromised_user_id} onChange={e=>form.setData('compromised_user_id',e.target.value)}>{hotel.superAdmins.map(a=><option key={a.id} value={a.id}>{a.email} · {a.status}</option>)}</select></Field><Field label="Promote existing staff (optional)"><select value={form.data.replacement_user_id} onChange={e=>form.setData('replacement_user_id',e.target.value)}><option value="">Create a new administrator</option>{hotel.recoveryCandidates.map(u=><option key={u.id} value={u.id}>{u.name} · {u.email}</option>)}</select></Field>{!form.data.replacement_user_id&&<div className="grid gap-4 sm:grid-cols-2"><Field label="First name"><input value={form.data.first_name} onChange={e=>form.setData('first_name',e.target.value)}/></Field><Field label="Last name"><input value={form.data.last_name} onChange={e=>form.setData('last_name',e.target.value)}/></Field><Field label="Email"><input type="email" value={form.data.email} onChange={e=>form.setData('email',e.target.value)}/></Field><Field label="Temporary password"><input type="password" value={form.data.password} onChange={e=>form.setData('password',e.target.value)}/></Field><Field label="Confirm password"><input type="password" value={form.data.password_confirmation} onChange={e=>form.setData('password_confirmation',e.target.value)}/></Field></div>}<Field label="Incident reason"><textarea rows={4} value={form.data.incident_reason} onChange={e=>form.setData('incident_reason',e.target.value)}/></Field><Field label="Your platform password"><input type="password" value={form.data.platform_password} onChange={e=>form.setData('platform_password',e.target.value)}/></Field><Field label="Type RECOVER to confirm"><input value={form.data.confirmation} onChange={e=>form.setData('confirmation',e.target.value)}/></Field>{Object.values(form.errors).length>0&&<p className="text-sm text-red-600">{String(Object.values(form.errors)[0])}</p>}<ModalActions close={close} processing={form.processing} label="Suspend and replace administrator"/></form></Modal>}

function ManageHotel({ hotel, plans, close }: { hotel:Hotel; plans:Plan[]; close:()=>void }) {
    const form = useForm({ name:hotel.name, slug:hotel.slug, status:hotel.status, timezone:hotel.timezone, currency:hotel.currency, plan_id:String(hotel.planId ?? ''), subscription_status:hotel.subscriptionStatus, trial_ends_at:(hotel.subscriptionStatus==='grace'?hotel.graceEndsAt:hotel.trialEndsAt)?.slice(0,10) ?? '' });
    const submit = (event:FormEvent) => { event.preventDefault(); form.patch(route('platform.hotels.update',hotel.id),{onSuccess:close}); };
    return <Modal title={`Manage ${hotel.name}`} subtitle="Update the property, subscription, and individual module access." close={close}><form onSubmit={submit} className="space-y-6"><FormSection title="Property and subscription"><div className="grid gap-4 sm:grid-cols-2"><Field label="Hotel name"><input value={form.data.name} onChange={e=>form.setData('name',e.target.value)}/></Field><Field label="Slug"><input value={form.data.slug} onChange={e=>form.setData('slug',e.target.value)}/></Field><Field label="Hotel status"><select value={form.data.status} onChange={e=>form.setData('status',e.target.value)}><option value="active">Active</option><option value="suspended">Suspended</option></select></Field><Field label="Subscription status"><select value={form.data.subscription_status} onChange={e=>form.setData('subscription_status',e.target.value)}>{['active','trialing','grace','past_due','cancelled','expired'].map(value=><option key={value}>{value}</option>)}</select></Field><Field label="Plan"><select value={form.data.plan_id} onChange={e=>form.setData('plan_id',e.target.value)}>{plans.map(plan=><option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></Field>{['trialing','grace'].includes(form.data.subscription_status)&&<Field label={form.data.subscription_status==='trialing'?'Trial end date':'Read-only access end date'}><input type="date" value={form.data.trial_ends_at} onChange={e=>form.setData('trial_ends_at',e.target.value)}/></Field>}<Field label="Timezone"><input value={form.data.timezone} onChange={e=>form.setData('timezone',e.target.value)}/></Field><Field label="Currency"><input value={form.data.currency} onChange={e=>form.setData('currency',e.target.value)}/></Field></div></FormSection><FormSection title="Module overrides" hint="Use plan inherits access from the selected subscription."><div className="grid gap-3 sm:grid-cols-2">{hotel.features.map(feature=><div key={feature.key} className="flex items-center justify-between gap-3 rounded-xl border border-slate-200 bg-white p-3"><div><p className="text-sm font-semibold">{feature.name}</p><p className={`mt-0.5 text-xs ${feature.enabled?'text-emerald-600':'text-slate-400'}`}>{feature.enabled?'Currently available':'Currently unavailable'}</p></div><select className="rounded-lg border border-slate-200 bg-slate-50 p-2 text-sm" defaultValue={feature.override===null?'inherit':feature.override?'enabled':'disabled'} onChange={e=>router.put(route('platform.hotels.features.update',[hotel.id,feature.key]),{mode:e.target.value},{preserveScroll:true})}><option value="inherit">Use plan</option><option value="enabled">Enabled</option><option value="disabled">Disabled</option></select></div>)}</div></FormSection><ModalActions close={close} processing={form.processing} label="Save changes"/></form></Modal>;
}

function Summary({icon,label,value,tone}:{icon:ReactNode;label:string;value:number;tone:'indigo'|'green'|'amber'|'blue'}) { const colors={indigo:'bg-indigo-50 text-indigo-700',green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',blue:'bg-sky-50 text-sky-700'}; return <div className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`rounded-2xl p-3 ${colors[tone]}`}>{icon}</div><div><p className="text-2xl font-bold">{value}</p><p className="text-sm text-slate-500">{label}</p></div></div>; }
function Metric({icon,label,value}:{icon:ReactNode;label:string;value:string|number}) { return <div className="rounded-xl border border-slate-100 bg-slate-50/60 p-3 text-left"><span className="text-slate-400">{icon}</span><p className="mt-2 text-base font-bold text-slate-800">{value}</p><p className="text-xs text-slate-500">{label}</p></div>; }
function Status({status}:{status:string}) { return <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-xs font-semibold capitalize ${status==='active'?'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200':'bg-red-50 text-red-700 ring-1 ring-red-200'}`}>{status==='active'?<CircleCheck size={13}/>:<CirclePause size={13}/>} {status}</span>; }
function Modal({title,subtitle,close,children}:{title:string;subtitle:string;close:()=>void;children:ReactNode}) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/60 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="max-h-[90vh] w-full max-w-3xl overflow-hidden rounded-2xl bg-white shadow-2xl"><div className="flex items-start justify-between border-b border-slate-100 px-6 py-5"><div><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-slate-500">{subtitle}</p></div><button onClick={close} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100 hover:text-slate-700"><X size={20}/></button></div><div className="max-h-[calc(90vh-92px)] overflow-y-auto p-6">{children}</div></div></div>; }
function FormSection({title,hint,children}:{title:string;hint?:string;children:ReactNode}) { return <section><div className="mb-4"><h3 className="text-base font-bold">{title}</h3>{hint&&<p className="mt-1 text-xs text-slate-500">{hint}</p>}</div>{children}</section>; }
function Field({label,error,children}:{label:string;error?:string;children:ReactNode}) { return <label className="block text-sm font-semibold text-slate-700">{label}<div className="mt-1.5 [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-slate-200 [&_input]:p-2.5 [&_input]:font-normal [&_input]:outline-none [&_input]:focus:border-indigo-400 [&_input]:focus:ring-4 [&_input]:focus:ring-indigo-100 [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-slate-200 [&_select]:p-2.5 [&_select]:font-normal [&_select]:outline-none">{children}</div>{error&&<span className="mt-1 block text-xs font-normal text-red-600">{error}</span>}</label>; }
function ModalActions({close,processing,label}:{close:()=>void;processing:boolean;label:string}) { return <div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={close} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700 hover:bg-slate-50">Cancel</button><button disabled={processing} className="rounded-lg bg-indigo-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-indigo-800 disabled:opacity-50">{processing?'Saving…':label}</button></div>; }
