import { PlatformLayout } from '@/components/layout/PlatformLayout';
import { Link } from '@inertiajs/react';
import { Activity, ArrowRight, Bed, Building2, CircleAlert, CircleCheck, CreditCard, Plus, Users } from 'lucide-react';
import { ReactNode } from 'react';

type Event={id:number;action:string;description:string;hotel:string;actor:string;severity:string;occurredAt:string};
type Backup={hotelId:number;hotelName:string;status:string;sizeBytes:number;records:number;files:number;missingFiles:number;createdAt:string|null;verifiedAt:string|null;ageHours:number|null;nextScheduledAt:string;needsAttention:boolean};
type Props={stats:{hotels:number;activeHotels:number;activeSubscriptions:number;attentionSubscriptions:number;rooms:number;staff:number;customRoles:number};plans:{id:number;name:string;subscribers:number}[];recentHotels:{id:number;name:string;slug:string;status:string;plan:string|null;subscriptionStatus:string|null;createdAt:string}[];recentActivity:Event[];operations:{id:number;name:string;offlineLocks:number;lowBatteryLocks:number;fcmFailures:number;backupIssue:boolean;status:string}[];backups:Backup[]};

export default function Overview({stats,plans,recentHotels,recentActivity,operations,backups}:Props){return <PlatformLayout>
    <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-indigo-600">Platform overview</p><h1 className="mt-2 text-3xl font-bold">Good to see you</h1><p className="mt-2 text-sm text-slate-500">A current view of clients, subscriptions, and platform operations.</p></div><Link href={route('platform.hotels.index')} className="flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-3 text-sm font-bold text-white"><Plus size={17}/>Manage properties</Link></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Building2/>} label="Client hotels" value={stats.hotels} note={`${stats.activeHotels} active`} tone="indigo"/><Stat icon={<CircleCheck/>} label="Subscriptions" value={stats.activeSubscriptions} note="Active, trial or grace" tone="green"/><Stat icon={<Bed/>} label="Rooms managed" value={stats.rooms} note="Across all properties" tone="amber"/><Stat icon={<Users/>} label="Staff accounts" value={stats.staff} note={`${stats.customRoles} custom roles configured`} tone="blue"/></section>
    {stats.attentionSubscriptions>0&&<div className="mt-5 flex items-center gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><CircleAlert size={20}/><strong>{stats.attentionSubscriptions} subscription{stats.attentionSubscriptions===1?'':'s'} need attention.</strong><Link href={route('platform.hotels.index')} className="ml-auto font-semibold underline">Review properties</Link></div>}
    <div className="mt-6"><Panel title="Property operations"><div className="space-y-3">{operations.map(hotel=><Link key={hotel.id} href={route('platform.hotels.onboarding',hotel.id)} className="grid gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 transition hover:border-amber-300 md:grid-cols-[1fr_auto_auto_auto_auto] md:items-center"><strong className="text-sm text-amber-950">{hotel.name}</strong><span className="text-xs font-semibold text-amber-800">{hotel.offlineLocks} offline locks</span><span className="text-xs font-semibold text-amber-800">{hotel.lowBatteryLocks} low batteries</span><span className="text-xs font-semibold text-amber-800">{hotel.fcmFailures} FCM failures</span><span className="text-xs font-semibold text-amber-800">Backup {hotel.backupIssue?'needs attention':'ready'}</span></Link>)}{operations.length===0&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">All property operations are within their configured thresholds.</div>}</div></Panel></div>
    <div className="mt-6"><Panel title="Backup health by property"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="border-b border-slate-100 text-xs uppercase tracking-wide text-slate-400"><th className="pb-3">Property</th><th className="pb-3">Status</th><th className="pb-3">Last backup</th><th className="pb-3">Verified</th><th className="pb-3">Contents</th><th className="pb-3">Next run</th><th className="pb-3 text-right">Manage</th></tr></thead><tbody className="divide-y divide-slate-100">{backups.map(b=><tr key={b.hotelId}><td className="py-4 font-bold">{b.hotelName}</td><td className="py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${b.needsAttention?'bg-amber-50 text-amber-700':'bg-emerald-50 text-emerald-700'}`}>{b.status}</span></td><td className="py-4"><p>{b.createdAt?new Date(b.createdAt).toLocaleString():'Never'}</p><p className="mt-1 text-xs text-slate-400">{b.ageHours===null?'No backup':`${b.ageHours}h ago`} · {(b.sizeBytes/1048576).toFixed(2)} MB</p></td><td className="py-4 text-slate-600">{b.verifiedAt?new Date(b.verifiedAt).toLocaleString():'Not verified'}</td><td className="py-4 text-slate-600">{b.records} records · {b.files} files{b.missingFiles?` · ${b.missingFiles} missing`:''}</td><td className="py-4 text-slate-600">{new Date(b.nextScheduledAt).toLocaleString()}</td><td className="py-4 text-right"><Link href={route('platform.hotels.onboarding',b.hotelId)} className="inline-flex items-center gap-1 font-semibold text-indigo-700">Manage <ArrowRight size={14}/></Link></td></tr>)}</tbody></table>{backups.length===0&&<Empty text="No properties are available for backup monitoring."/>}</div></Panel></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.4fr_1fr]">
      <Panel title="Recently added properties" action={<Link href={route('platform.hotels.index')} className="flex items-center gap-1 text-sm font-semibold text-indigo-700">View all <ArrowRight size={15}/></Link>}><div className="divide-y divide-slate-100">{recentHotels.map(h=><div key={h.id} className="flex items-center gap-3 py-4 first:pt-1 last:pb-1"><div className="rounded-xl bg-indigo-50 p-2.5 text-indigo-700"><Building2 size={18}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{h.name}</p><p className="text-xs text-slate-500">/{h.slug} · {h.plan??'No plan'}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${h.status==='active'?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}>{h.status}</span></div>)}{recentHotels.length===0&&<Empty text="No client hotels yet."/>}</div></Panel>
      <Panel title="Plan distribution" action={<Link href={route('platform.plans.index')} className="flex items-center gap-1 text-sm font-semibold text-indigo-700">Plans <ArrowRight size={15}/></Link>}><div className="space-y-3">{plans.map(plan=><div key={plan.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3"><span className="flex items-center gap-2 text-sm font-semibold"><CreditCard size={16} className="text-slate-400"/>{plan.name}</span><span className="rounded-full bg-white px-2.5 py-1 text-xs font-bold text-slate-600 shadow-sm">{plan.subscribers}</span></div>)}</div></Panel>
    </div>
    <div className="mt-6"><Panel title="Recent platform activity" action={<Link href={route('platform.activity.index')} className="flex items-center gap-1 text-sm font-semibold text-indigo-700">Full activity <ArrowRight size={15}/></Link>}><div className="divide-y divide-slate-100">{recentActivity.map(event=><div key={event.id} className="flex gap-3 py-4 first:pt-1 last:pb-1"><div className="mt-0.5 rounded-lg bg-slate-100 p-2 text-slate-500"><Activity size={16}/></div><div className="flex-1"><p className="text-sm font-semibold">{event.description}</p><p className="mt-1 text-xs text-slate-500">{event.hotel} · {event.actor} · {new Date(event.occurredAt).toLocaleString()}</p></div></div>)}{recentActivity.length===0&&<Empty text="No platform actions have been recorded yet."/>}</div></Panel></div>
  </PlatformLayout>}

function Stat({icon,label,value,note,tone}:{icon:ReactNode;label:string;value:number;note:string;tone:string}){const colors:{[key:string]:string}={indigo:'bg-indigo-50 text-indigo-700',green:'bg-emerald-50 text-emerald-700',amber:'bg-amber-50 text-amber-700',blue:'bg-sky-50 text-sky-700'};return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`w-fit rounded-2xl p-3 ${colors[tone]}`}>{icon}</div><p className="mt-4 text-3xl font-bold">{value}</p><p className="mt-1 text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-slate-500">{note}</p></div>}
function Panel({title,action,children}:{title:string;action?:ReactNode;children:ReactNode}){return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-base font-bold">{title}</h2>{action}</div>{children}</section>}
function Empty({text}:{text:string}){return <p className="py-8 text-center text-sm text-slate-400">{text}</p>}
