<?php
namespace App\Services\Notifications;
use App\Models\{Hotel,HotelIntegration};use Illuminate\Support\Facades\{Cache,Http};use RuntimeException;
class FcmClient{public function configured(?Hotel$hotel=null):bool{return$this->account($hotel)!==null;}public function source(?Hotel$hotel=null):string{return$this->configured($hotel)?'hotel':'none';}
public function details(?Hotel$hotel=null):array{$i=$hotel?HotelIntegration::where('hotel_id',$hotel->id)->where('type','fcm')->first():null;$c=$i?->configuration??[];return['source'=>$this->source($hotel),'configured'=>$this->configured($hotel),'active'=>$i?->active??false,'project_id'=>$c['project_id']??null,'client_email'=>$c['client_email']??null,'api_key'=>$c['api_key']??null,'messaging_sender_id'=>$c['messaging_sender_id']??null,'android_app_id'=>$c['android_app_id']??null,'ios_app_id'=>$c['ios_app_id']??null,'has_private_key'=>filled($c['private_key']??null),'connection_status'=>$i?->connection_status??'unconfigured','last_error'=>$i?->last_error,'last_tested_at'=>$i?->last_tested_at?->toISOString()];}
public function send(string$token,string$title,string$body,array$data=[],?Hotel$hotel=null):void{$account=$this->account($hotel);if(!$account)throw new RuntimeException('Firebase Cloud Messaging is not configured.');Http::withToken($this->accessToken($account,$hotel))->post("https://fcm.googleapis.com/v1/projects/{$account['project_id']}/messages:send",['message'=>['token'=>$token,'notification'=>['title'=>$title,'body'=>$body],'data'=>collect($data)->map(fn($v)=>is_scalar($v)?(string)$v:json_encode($v))->all(),'android'=>['priority'=>'high'],'apns'=>['payload'=>['aps'=>['sound'=>'default']]]]])->throw();}
public function test(Hotel$hotel):void{$account=$this->account($hotel);if(!$account)throw new RuntimeException('Firebase Cloud Messaging is not configured.');$this->accessToken($account,$hotel,true);}
private function account(?Hotel$hotel):?array{if(!$hotel)return null;$i=HotelIntegration::where('hotel_id',$hotel->id)->where('type','fcm')->where('active',true)->first();if(!$i)return null;$c=$i->configuration;return filled($c['project_id']??null)&&filled($c['client_email']??null)&&filled($c['private_key']??null)?$c:null;}
private function accessToken(array$a,?Hotel$hotel,bool$fresh=false):string{$key='fcm.oauth-token.'.($hotel?->id??'global').'.'.hash('sha256',$a['client_email'].$a['project_id']);if($fresh)Cache::forget($key);return Cache::remember($key,3300,function()use($a){$now=time();$uri=$a['token_uri']??'https://oauth2.googleapis.com/token';$header=$this->encode(['alg'=>'RS256','typ'=>'JWT']);$claims=$this->encode(['iss'=>$a['client_email'],'scope'=>'https://www.googleapis.com/auth/firebase.messaging','aud'=>$uri,'iat'=>$now,'exp'=>$now+3600]);if(!openssl_sign("{$header}.{$claims}",$signature,$a['private_key'],OPENSSL_ALGO_SHA256))throw new RuntimeException('The Firebase private key is invalid.');$jwt="{$header}.{$claims}.".$this->base64($signature);return Http::asForm()->post($uri,['grant_type'=>'urn:ietf:params:oauth:grant-type:jwt-bearer','assertion'=>$jwt])->throw()->json('access_token')??throw new RuntimeException('Firebase did not return an access token.');});}
private function encode(array$v):string{return$this->base64(json_encode($v,JSON_UNESCAPED_SLASHES));}private function base64(string$v):string{return rtrim(strtr(base64_encode($v),'+/','-_'),'=');}}
