<?php
namespace App\Services\Locks;
use App\Models\{LockDevice,LockProviderConfig};use Illuminate\Support\Facades\Http;use Illuminate\Support\Str;use RuntimeException;
class ProviderManager implements LockProvider{
 public function provision(LockDevice$device,string$type,\DateTimeInterface$from,\DateTimeInterface$until):array{if($device->provider==='simulator')return['external_id'=>'sim-'.Str::uuid(),'secret'=>strtoupper(Str::random(8))];$r=$this->client($device->provider)->post("devices/{$device->external_id}/credentials",['type'=>$type,'valid_from'=>$from->format(DATE_ATOM),'valid_until'=>$until->format(DATE_ATOM)])->throw()->json();return['external_id'=>$r['external_id']??throw new RuntimeException('Provider did not return a credential ID.'),'secret'=>$r['secret']??''];}
 public function revoke(LockDevice$device,string$id):void{if($device->provider==='simulator')return;$this->client($device->provider)->delete("devices/{$device->external_id}/credentials/{$id}")->throw();}
 public function unlock(LockDevice$device):array{if($device->provider==='simulator')return['external_id'=>'cmd-'.Str::uuid(),'status'=>'completed'];$r=$this->client($device->provider)->post("devices/{$device->external_id}/unlock")->throw()->json();return['external_id'=>$r['external_id']??null,'status'=>$r['status']??'completed','provider_response'=>$r];}
 public function status(LockDevice$device):array{if($device->provider==='simulator')return['status'=>'online','battery_level'=>$device->battery_level,'last_seen_at'=>now(),'sync_status'=>'synced','last_synced_at'=>now()];$r=$this->client($device->provider)->get("devices/{$device->external_id}")->throw()->json();return['status'=>$r['status']??'unknown','battery_level'=>(int)($r['battery_level']??$device->battery_level),'firmware_version'=>$r['firmware_version']??$device->firmware_version,'hardware_model'=>$r['hardware_model']??$device->hardware_model,'capabilities'=>$r['capabilities']??$device->capabilities,'last_seen_at'=>isset($r['last_seen_at'])?\Carbon\Carbon::parse($r['last_seen_at']):now(),'sync_status'=>'synced','sync_error'=>null,'last_synced_at'=>now()];}
 public function test(LockProviderConfig$config):array{if($config->driver==='simulator')return['ok'=>true,'message'=>'Simulator is ready.'];$r=$this->client($config->key)->get('health')->throw()->json();return['ok'=>true,'message'=>$r['message']??'Provider connection successful.'];}
 public function discover(LockProviderConfig$config):array{if($config->driver==='simulator')return[];$data=$this->client($config->key)->get('devices')->throw()->json();return array_values($data['data']??$data['devices']??[]);}
 private function client(string$key){$config=LockProviderConfig::where('key',$key)->where('active',true)->firstOrFail();$token=$config->credentials['token']??null;return Http::baseUrl(rtrim((string)$config->base_url,'/').'/')->acceptJson()->timeout(12)->retry(2,300)->when($token,fn($request)=>$request->withToken($token));}
}
