import { FormEvent, useMemo, useState } from 'react';
import { router, useForm } from '@inertiajs/react';
import { AlertTriangle, ClipboardPlus, Clock } from 'lucide-react';
import { AdminLayout } from '@/components/layout/AdminLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { GuestRequestConversation, type GuestRequestThread } from '@/components/GuestRequestConversation';

type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'inspected' | 'maintenance_required' | 'cancelled';
type ChecklistItem = { label: string; completed: boolean };
type Task = { id:number; roomNumber:string; roomId:number; taskType:string; status:TaskStatus; priority:string; dueAt:string|null; isOverdue:boolean; notes:string|null; checklist:ChecklistItem[]; assignedTo:number|null; assignee:string|null; assignedBy:string|null; assignedAt:string|null; reassignmentReason:string|null; startedAt:string|null; completedAt:string|null; maintenanceNotes:string|null;guestRequest:GuestRequestThread|null };
type Worker = { id:number; name:string };
type Room = { id:number; number:string; status:string };
type ActiveGuest = {id:number;name:string;roomId:number};
type Filter = 'active' | 'pending' | 'in_progress' | 'completed' | 'overdue' | 'archive';

const statusLabel: Record<TaskStatus, string> = { pending:'Pending housekeeping', in_progress:'Cleaning in progress', completed:'Awaiting inspection', inspected:'Inspected', maintenance_required:'Maintenance required',cancelled:'Cancelled' };
const statusStyle: Record<TaskStatus, string> = { pending:'bg-amber-100 text-amber-800', in_progress:'bg-blue-100 text-blue-800', completed:'bg-purple-100 text-purple-800', inspected:'bg-green-100 text-green-800', maintenance_required:'bg-red-100 text-red-800',cancelled:'bg-gray-200 text-gray-700' };

export default function Housekeeping({ tasks, workers, rooms, activeGuests, canInspect, isHousekeeper }:{tasks:Task[];workers:Worker[];rooms:Room[];activeGuests:ActiveGuest[];canInspect:boolean;isHousekeeper:boolean}) {
  const [filter,setFilter]=useState<Filter>('active');
  const [open,setOpen]=useState(false);
  const shown=useMemo(()=>tasks.filter(task=>{
    if(filter==='active')return !['inspected','maintenance_required','cancelled'].includes(task.status);
    if(filter==='overdue')return task.isOverdue;
    if(filter==='archive')return ['inspected','maintenance_required','cancelled'].includes(task.status);
    return task.status===filter;
  }),[tasks,filter]);
  const form=useForm({room_id:'',guest_id:'',task_type:'turnover',assigned_to:'',priority:'normal',due_at:'',notes:''});
  const create=(event:FormEvent)=>{event.preventDefault();form.post(route('dashboard.housekeeping.store'),{preserveScroll:true,onSuccess:()=>{setOpen(false);form.reset()}})};

  return <AdminLayout title="Housekeeping">
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Housekeeping queue</h1><p className="text-gray-600">Assign rooms, track room readiness, and inspect completed work.</p></div><div className="flex gap-2">{isHousekeeper&&<Button variant="outline" onClick={()=>router.get(route('dashboard.housekeeping.index'),{scope:'all'},{preserveState:true})}>View all tasks</Button>}<Button onClick={()=>setOpen(true)}><ClipboardPlus className="mr-2" size={16}/>New request</Button></div></div>
    <div className="mb-5 flex flex-wrap gap-2">{(['active','pending','in_progress','completed','overdue','archive'] as Filter[]).map(value=><Button key={value} size="sm" variant={filter===value?'default':'outline'} onClick={()=>setFilter(value)} className="capitalize">{value.replace('_',' ')}</Button>)}</div>
    <div className="grid gap-4 lg:grid-cols-2">{shown.map(task=><TaskCard key={task.id} task={task} workers={workers} canInspect={canInspect}/>)}{shown.length===0&&<div className="col-span-full rounded-lg bg-white p-10 text-center text-gray-500">No housekeeping tasks in this view.</div>}</div>
    {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onMouseDown={()=>setOpen(false)}><form onSubmit={create} onMouseDown={event=>event.stopPropagation()} className="w-full max-w-xl rounded-lg bg-white p-6 shadow-xl"><h2 className="text-xl font-semibold">Create housekeeping request</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><Field label="Room" error={form.errors.room_id}><select className="w-full rounded-md border p-2" value={form.data.room_id} onChange={e=>{form.setData('room_id',e.target.value);form.setData('guest_id','')}} required><option value="">Select room</option>{rooms.map(room=><option key={room.id} value={room.id}>Room {room.number} · {room.status}</option>)}</select></Field><Field label="Create for guest (optional)" error={form.errors.guest_id}><select className="w-full rounded-md border p-2" value={form.data.guest_id} onChange={e=>form.setData('guest_id',e.target.value)} disabled={!form.data.room_id}><option value="">No guest conversation</option>{activeGuests.filter(g=>String(g.roomId)===form.data.room_id).map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="Request type" error={form.errors.task_type}><select className="w-full rounded-md border p-2" value={form.data.task_type} onChange={e=>form.setData('task_type',e.target.value)}><option value="turnover">Room turnover</option><option value="service">Guest service</option><option value="inspection">Inspection</option></select></Field><Field label="Assign housekeeper" error={form.errors.assigned_to}><select className="w-full rounded-md border p-2" value={form.data.assigned_to} onChange={e=>form.setData('assigned_to',e.target.value)}><option value="">Leave unassigned</option>{workers.map(worker=><option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></Field><Field label="Priority" error={form.errors.priority}><select className="w-full rounded-md border p-2" value={form.data.priority} onChange={e=>form.setData('priority',e.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field><Field label="Due by" error={form.errors.due_at}><Input type="datetime-local" value={form.data.due_at} onChange={e=>form.setData('due_at',e.target.value)}/></Field><div className="md:col-span-2"><Field label="Instructions" error={form.errors.notes}><textarea className="min-h-24 w-full rounded-md border p-2" value={form.data.notes} onChange={e=>form.setData('notes',e.target.value)} placeholder="Special cleaning instructions…"/></Field></div></div><div className="mt-6 flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={form.processing}>Create request</Button></div></form></div>}
  </AdminLayout>;
}

function TaskCard({task,workers,canInspect}:{task:Task;workers:Worker[];canInspect:boolean}) {
  const [notes,setNotes]=useState(task.notes??'');const[priority,setPriority]=useState(task.priority);const[dueAt,setDueAt]=useState(task.dueAt?task.dueAt.slice(0,16):'');
  const update=(changes:Partial<Task>&{reassignment_reason?:string|null}={})=>router.patch(route('dashboard.housekeeping.update',task.id),{status:task.status,assigned_to:task.assignedTo,priority,notes,due_at:dueAt||null,checklist:task.checklist,maintenance_notes:task.maintenanceNotes??'',...changes},{preserveScroll:true});
  const assign=(value:string)=>{const next=value?Number(value):null;let reason:string|null=null;if(task.assignedTo&&next&&next!==task.assignedTo){reason=window.prompt('Why is this task being reassigned?');if(!reason)return}update({assignedTo:next,assigned_to:next,reassignment_reason:reason} as Partial<Task>&{assigned_to:number|null;reassignment_reason:string|null})};
  const toggle=(index:number)=>update({checklist:task.checklist.map((item,i)=>i===index?{...item,completed:!item.completed}:item)});
  const maintenance=()=>{const reason=window.prompt('Describe the maintenance issue:');if(reason)update({status:'maintenance_required',maintenanceNotes:reason,maintenance_notes:reason} as Partial<Task>)};
  return <div className={`rounded-lg bg-white p-6 shadow ${task.isOverdue?'ring-2 ring-red-300':''}`}><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">Room {task.roomNumber}</h2><p className="text-sm capitalize text-gray-500">{task.taskType.replace('_',' ')} · {task.priority} priority</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${statusStyle[task.status]}`}>{statusLabel[task.status]}</span></div>{task.isOverdue&&<p className="mt-3 flex items-center gap-1 text-sm font-medium text-red-600"><Clock size={15}/>Overdue</p>}
    <label className="mt-4 block text-sm font-medium">Assigned housekeeper<select className="mt-1 w-full rounded-md border p-2" value={task.assignedTo??''} disabled={['inspected','maintenance_required','cancelled'].includes(task.status)} onChange={e=>assign(e.target.value)}><option value="">Unassigned — select a worker</option>{workers.map(worker=><option key={worker.id} value={worker.id}>{worker.name}</option>)}</select></label>{task.assignedAt&&<p className="mt-1 text-xs text-gray-500">Assigned {new Date(task.assignedAt).toLocaleString()}{task.assignedBy&&` by ${task.assignedBy}`}</p>}
    {!['inspected','maintenance_required','cancelled'].includes(task.status)&&<><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Priority"><select className="w-full rounded-md border p-2" value={priority} onChange={e=>setPriority(e.target.value)}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field><Field label="Due by"><Input type="datetime-local" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></Field></div><Field label="Instructions"><textarea className="mt-1 min-h-20 w-full rounded-md border p-2" value={notes} onChange={e=>setNotes(e.target.value)}/></Field><div className="mt-2 flex justify-end"><Button size="sm" variant="outline" onClick={()=>update()}>Save details</Button></div></>}
    {task.status==='in_progress'&&<div className="mt-5 rounded-md bg-gray-50 p-4"><h3 className="text-sm font-semibold">Room readiness checklist</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{task.checklist.map((item,index)=><label key={item.label} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={item.completed} onChange={()=>toggle(index)}/>{item.label}</label>)}</div></div>}
    {task.maintenanceNotes&&<p className="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-700"><strong>Maintenance:</strong> {task.maintenanceNotes}</p>}
    <div className="mt-5 flex flex-wrap justify-end gap-2">{task.status==='pending'&&<Button disabled={!task.assignedTo} onClick={()=>update({status:'in_progress'})}>Start cleaning</Button>}{task.status==='in_progress'&&<><Button variant="outline" className="text-red-600" onClick={maintenance}><AlertTriangle className="mr-2" size={15}/>Report maintenance</Button><Button onClick={()=>update({status:'completed'})}>Mark completed</Button></>}{task.status==='completed'&&canInspect&&<><Button variant="outline" className="text-red-600" onClick={maintenance}>Fail to maintenance</Button><Button onClick={()=>update({status:'inspected'})}>Inspect &amp; release room</Button></>}</div>{task.guestRequest&&<GuestRequestConversation request={task.guestRequest}/>} 
  </div>;
}

function Field({label,error,children}:{label:string;error?:string;children:React.ReactNode}){return <label className="block text-sm font-medium text-gray-700"><span>{label}</span><div className="mt-1">{children}</div>{error&&<span className="mt-1 block text-sm text-red-600">{error}</span>}</label>}
