<?php
namespace App\Http\Controllers\Platform;
use App\Http\Controllers\Controller;use App\Models\{BillingWebhookEvent,Hotel,HotelSubscription,Plan,User};use App\Services\Billing\StripeBilling;use Illuminate\Http\{JsonResponse,RedirectResponse,Request};use Inertia\{Inertia,Response};use Throwable;
class BillingController extends Controller{public function index():Response{return Inertia::render('Platform/Billing',['configured'=>filled(config('services.stripe.secret')),'webhookConfigured'=>filled(config('services.stripe.webhook_secret')),'hotels'=>Hotel::with('subscription.plan')->orderBy('name')->get()->map(fn($h)=>['id'=>$h->id,'name'=>$h->name,'plan'=>$h->subscription?->plan?->name,'status'=>$h->subscription?->status??'inactive','provider'=>$h->subscription?->provider,'customerId'=>$h->subscription?->provider_customer_id,'periodEnds'=>$h->subscription?->current_period_ends_at?->toISOString()]),'plans'=>Plan::where('active',true)->orderBy('id')->get()->map(fn($p)=>['id'=>$p->id,'name'=>$p->name,'key'=>$p->key,'monthlyPrice'=>$p->monthly_price,'configured'=>filled($p->stripe_price_id?:env('STRIPE_PRICE_'.strtoupper($p->key)))])]);}
public function checkout(Request$r,Hotel$hotel,StripeBilling$stripe):RedirectResponse{$data=$r->validate(['plan_id'=>'required|exists:plans,id']);$plan=Plan::findOrFail($data['plan_id']);$admin=User::withoutGlobalScopes()->where('hotel_id',$hotel->id)->where('role','super_admin')->firstOrFail();try{return redirect()->away($stripe->checkout($hotel,$plan,$admin->email));}catch(Throwable$e){return back()->withErrors(['billing'=>$e->getMessage()]);}}
public function portal(Hotel$hotel,StripeBilling$stripe):RedirectResponse{try{return redirect()->away($stripe->portal($hotel));}catch(Throwable$e){return back()->withErrors(['billing'=>$e->getMessage()]);}}
public function webhook(Request$r):JsonResponse{$payload=$r->getContent();if(!$this->validSignature($payload,(string)$r->header('Stripe-Signature')))return response()->json(['message'=>'Invalid signature.'],400);$event=json_decode($payload,true);if(!is_array($event)||blank($event['id']??null))return response()->json(['message'=>'Invalid payload.'],400);$record=BillingWebhookEvent::firstOrCreate(['provider_event_id'=>$event['id']],['provider'=>'stripe','type'=>$event['type']??'unknown']);if(!$record->wasRecentlyCreated)return response()->json(['received'=>true]);try{$this->apply($event);$record->update(['status'=>'processed','processed_at'=>now()]);}catch(Throwable$e){$record->update(['status'=>'failed','error'=>$e->getMessage()]);throw$e;}return response()->json(['received'=>true]);}
private function apply(array$event):void{$object=$event['data']['object']??[];$type=$event['type']??'';$hotelId=$object['metadata']['hotel_id']??$object['client_reference_id']??null;$subscriptionId=is_string($object['subscription']??null)?$object['subscription']:($object['id']??null);if(!$hotelId&&isset($object['customer']))$hotelId=HotelSubscription::where('provider_customer_id',$object['customer'])->value('hotel_id');if(!$hotelId)return;$subscription=HotelSubscription::firstOrNew(['hotel_id'=>$hotelId]);if($type==='checkout.session.completed'){$subscription->provider='stripe';$subscription->provider_customer_id=$object['customer']??$subscription->provider_customer_id;$subscription->provider_subscription_id=$object['subscription']??$subscription->provider_subscription_id;$subscription->plan_id=(int)($object['metadata']['plan_id']??$subscription->plan_id);$subscription->status='active';$subscription->save();return;}if(str_starts_with($type,'customer.subscription.')){$priceId=$object['items']['data'][0]['price']['id']??null;$plan=Plan::where('stripe_price_id',$priceId)->first()??Plan::all()->first(fn(Plan$p)=>env('STRIPE_PRICE_'.strtoupper($p->key))===$priceId);if($plan)$subscription->plan_id=$plan->id;$subscription->provider='stripe';$subscription->provider_customer_id=$object['customer']??$subscription->provider_customer_id;$subscription->provider_subscription_id=$subscriptionId;$subscription->status=$type==='customer.subscription.deleted'?'cancelled':$this->status($object['status']??'active');$subscription->current_period_ends_at=isset($object['current_period_end'])?date('Y-m-d H:i:s',$object['current_period_end']):null;$subscription->save();return;}if($type==='invoice.payment_failed'){$subscription->status='past_due';$subscription->save();}elseif($type==='invoice.paid'){$subscription->status='active';$subscription->save();}}
private function status(string$status):string{return match($status){'trialing'=>'trialing','past_due','unpaid','incomplete','incomplete_expired'=>'past_due','canceled','paused'=>'cancelled',default=>'active'};}
private function validSignature(string$payload,string$header):bool{$secret=(string)config('services.stripe.webhook_secret');if(blank($secret)||blank($header))return false;$parts=[];foreach(explode(',',$header)as$part){[$k,$v]=array_pad(explode('=',$part,2),2,null);$parts[$k][]=$v;}$timestamp=(int)($parts['t'][0]??0);if(!$timestamp||abs(time()-$timestamp)>300)return false;$expected=hash_hmac('sha256',$timestamp.'.'.$payload,$secret);foreach($parts['v1']??[]as$signature)if(hash_equals($expected,(string)$signature))return true;return false;}}
