import { AdminLayout } from '@/components/layout/AdminLayout';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Link, router } from '@inertiajs/react';
import { Building2, Download, FilePlus2, Landmark, MoveRight } from 'lucide-react';

type Aging = { current: number; days_1_30: number; days_31_60: number; days_61_90: number; days_90_plus: number };
type Account = { id: number; name: string; code: string; status: string; terms: number; invoiceCount: number; balance: number };
type Group = { id: number; code: string; name: string; account: string | null; eligibleCharges: number; masterFolioId: number | null; masterBalance: number; uninvoicedCharges: number };
type Invoice = { id: number; number: string; account: string; group: string | null; status: string; issueDate: string; dueDate: string; total: number; paid: number; balance: number };

const statusStyle: Record<string, string> = { paid: 'bg-emerald-100 text-emerald-800', issued: 'bg-blue-100 text-blue-800', partially_paid: 'bg-amber-100 text-amber-800', overdue: 'bg-red-100 text-red-800', void: 'bg-slate-200 text-slate-700' };

export default function Index({ currency, aging, accounts, groups, invoices }: { currency: string; aging: Aging; accounts: Account[]; groups: Group[]; invoices: Invoice[] }) {
    const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency }).format(value);
    const transfer = (group: Group) => router.post(route('dashboard.groups.master-folio.transfer', group.id), {}, { preserveScroll: true });
    const issue = (group: Group) => router.post(route('dashboard.groups.invoices.store', group.id), {}, { preserveScroll: true });
    const buckets: [string, keyof Aging][] = [['Current', 'current'], ['1–30 days', 'days_1_30'], ['31–60 days', 'days_31_60'], ['61–90 days', 'days_61_90'], ['90+ days', 'days_90_plus']];

    return <AdminLayout title="Accounts Receivable"><div className="space-y-6">
        <header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-2xl font-bold">Accounts receivable</h1><p className="text-gray-600">Consolidate group charges, invoice company accounts, and track collections.</p></div><Button variant="outline" onClick={() => window.print()}>Print aging report</Button></header>
        <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{buckets.map(([label, key]) => <Card key={key} className={key === 'days_90_plus' ? 'border-red-200' : ''}><CardContent className="p-5"><p className="text-sm text-gray-500">{label}</p><p className="mt-2 text-xl font-bold">{money(aging[key])}</p></CardContent></Card>)}</section>
        <Card className="overflow-hidden"><CardHeader><CardTitle className="flex items-center gap-2"><MoveRight size={20}/>Group billing pipeline</CardTitle></CardHeader><CardContent className="grid gap-4 xl:grid-cols-2">{groups.length ? groups.map(group => <div key={group.id} className="rounded-xl border bg-slate-50 p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{group.name} <span className="text-sm text-gray-500">({group.code})</span></p><p className="text-sm text-gray-600">{group.account}</p></div><p className="font-semibold">Master balance: {money(group.masterBalance)}</p></div><div className="mt-4 flex flex-wrap items-center gap-2"><Button size="sm" disabled={!group.eligibleCharges} onClick={() => transfer(group)}><MoveRight className="mr-2" size={15}/>Transfer {group.eligibleCharges} charge{group.eligibleCharges === 1 ? '' : 's'}</Button><Button size="sm" variant="outline" asChild><Link href={route('dashboard.groups.master-folio', group.id)}>Open master folio</Link></Button><Button size="sm" variant="secondary" disabled={!group.uninvoicedCharges} onClick={() => issue(group)}><FilePlus2 className="mr-2" size={15}/>Issue invoice ({group.uninvoicedCharges})</Button></div></div>) : <p className="text-sm text-gray-500">No corporate group billing is waiting.</p>}</CardContent></Card>
        <div className="grid gap-6 xl:grid-cols-[0.85fr_1.6fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2"><Building2 size={20}/>Company accounts</CardTitle></CardHeader><CardContent className="space-y-3">{accounts.map(account => <div key={account.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{account.name}</p><p className="text-xs text-gray-500">{account.code} · Net {account.terms}</p></div><p className="font-bold">{money(account.balance)}</p></div><div className="mt-3 flex items-center justify-between"><span className="text-xs text-gray-500">{account.invoiceCount} invoice{account.invoiceCount === 1 ? '' : 's'}</span><Button variant="ghost" size="sm" asChild><a href={route('dashboard.corporate-accounts.statement', account.id)}><Download className="mr-2" size={14}/>Statement</a></Button></div></div>)}</CardContent></Card>
        <Card className="overflow-hidden"><CardHeader><CardTitle className="flex items-center gap-2"><Landmark size={20}/>Corporate invoices</CardTitle></CardHeader><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-gray-500"><tr><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Account</th><th className="px-5 py-3">Due</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Total</th><th className="px-5 py-3 text-right">Balance</th></tr></thead><tbody className="divide-y">{invoices.map(invoice => <tr key={invoice.id} className="hover:bg-slate-50"><td className="px-5 py-4"><Link className="font-semibold text-blue-700 hover:underline" href={route('dashboard.corporate-invoices.show', invoice.id)}>{invoice.number}</Link><p className="text-xs text-gray-500">{invoice.issueDate}</p></td><td className="px-5 py-4">{invoice.account}<p className="text-xs text-gray-500">{invoice.group}</p></td><td className="px-5 py-4">{invoice.dueDate}</td><td className="px-5 py-4"><Badge className={statusStyle[invoice.status]}>{invoice.status.replace('_', ' ')}</Badge></td><td className="px-5 py-4 text-right">{money(invoice.total)}</td><td className="px-5 py-4 text-right font-semibold">{money(invoice.balance)}</td></tr>)}{!invoices.length && <tr><td colSpan={6} className="px-5 py-10 text-center text-gray-500">No corporate invoices have been issued.</td></tr>}</tbody></table></div></CardContent></Card></div>
    </div></AdminLayout>;
}
