import { AdminLayout } from '@/components/layout/AdminLayout';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { Link, useForm } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

type Item = { id: number; description: string; guest: string | null; amount: number; tax: number; total: number };
type Payment = { id: number; type: string; method: string; amount: number; reference: string | null; notes: string | null; processedAt: string };
type Invoice = { id: number; number: string; account: string; accountCode: string; billingAddress: string | null; taxNumber: string | null; group: string | null; status: string; currency: string; issueDate: string; dueDate: string; subtotal: number; tax: number; total: number; paid: number; balance: number; notes: string | null; voidReason: string | null; items: Item[]; payments: Payment[] };

export default function Show({ invoice }: { invoice: Invoice }) {
    const [mode, setMode] = useState<'payment' | 'credit' | 'void' | null>(null);
    const payment = useForm({ amount: String(invoice.balance), method: 'bank_transfer', reference: '', notes: '' });
    const credit = useForm({ amount: String(invoice.balance), notes: '' });
    const voidForm = useForm({ reason: '' });
    const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: invoice.currency }).format(value);
    const submit = (event: FormEvent) => { event.preventDefault(); if (mode === 'payment') payment.post(route('dashboard.corporate-invoices.payments.store', invoice.id), { onSuccess: () => setMode(null) }); if (mode === 'credit') credit.post(route('dashboard.corporate-invoices.credits.store', invoice.id), { onSuccess: () => setMode(null) }); if (mode === 'void') voidForm.patch(route('dashboard.corporate-invoices.void', invoice.id), { onSuccess: () => setMode(null) }); };
    const open = !['paid', 'void'].includes(invoice.status);

    return <AdminLayout title={invoice.number}><div className="mx-auto max-w-5xl space-y-6"><div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><Button variant="ghost" asChild><Link href={route('dashboard.receivables.index')}>← Accounts receivable</Link></Button><div className="flex gap-2"><Button variant="outline" onClick={() => window.print()}>Print / Save PDF</Button>{open && <><Button variant="outline" onClick={() => setMode('credit')}>Credit note</Button><Button onClick={() => setMode('payment')}>Record payment</Button><Button variant="destructive" onClick={() => setMode('void')}>Void</Button></>}</div></div>
        <Card className="print:border-0 print:shadow-none"><CardContent className="p-7 sm:p-10"><header className="flex flex-wrap justify-between gap-6 border-b pb-7"><div><p className="text-sm font-semibold uppercase tracking-widest text-gray-500">Corporate invoice</p><h1 className="mt-2 text-3xl font-bold">{invoice.number}</h1><Badge className="mt-3">{invoice.status.replace('_', ' ')}</Badge></div><div className="text-right text-sm"><p><strong>Issued:</strong> {invoice.issueDate}</p><p><strong>Due:</strong> {invoice.dueDate}</p></div></header><section className="grid gap-6 border-b py-7 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase text-gray-500">Bill to</p><p className="mt-2 font-semibold">{invoice.account}</p><p className="whitespace-pre-line text-sm text-gray-600">{invoice.billingAddress}</p>{invoice.taxNumber && <p className="text-sm text-gray-600">Tax ID: {invoice.taxNumber}</p>}</div><div className="sm:text-right"><p className="text-xs font-semibold uppercase text-gray-500">Group</p><p className="mt-2 font-semibold">{invoice.group || 'Corporate account'}</p><p className="text-sm text-gray-600">Account {invoice.accountCode}</p></div></section><div className="overflow-x-auto py-6"><table className="w-full text-sm"><thead><tr className="border-b text-left text-xs uppercase text-gray-500"><th className="py-3">Description</th><th className="py-3">Guest</th><th className="py-3 text-right">Net</th><th className="py-3 text-right">Tax</th><th className="py-3 text-right">Total</th></tr></thead><tbody className="divide-y">{invoice.items.map(item => <tr key={item.id}><td className="py-4">{item.description}</td><td className="py-4 text-gray-600">{item.guest || '—'}</td><td className="py-4 text-right">{money(item.amount)}</td><td className="py-4 text-right">{money(item.tax)}</td><td className="py-4 text-right font-medium">{money(item.total)}</td></tr>)}</tbody></table></div><div className="ml-auto max-w-sm space-y-2 border-t pt-5 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>{money(invoice.subtotal)}</span></div><div className="flex justify-between"><span>Tax</span><span>{money(invoice.tax)}</span></div><div className="flex justify-between text-base font-semibold"><span>Total</span><span>{money(invoice.total)}</span></div><div className="flex justify-between text-gray-600"><span>Payments</span><span>− {money(invoice.paid)}</span></div><div className="flex justify-between border-t pt-3 text-xl font-bold"><span>Balance due</span><span>{money(invoice.balance)}</span></div></div>{invoice.notes && <div className="mt-8 rounded-lg bg-slate-50 p-4 text-sm"><strong>Notes:</strong> {invoice.notes}</div>}{invoice.voidReason && <div className="mt-4 rounded-lg bg-red-50 p-4 text-sm text-red-800"><strong>Void reason:</strong> {invoice.voidReason}</div>}</CardContent></Card>
        {!!invoice.payments.length && <Card className="print:hidden"><CardHeader><CardTitle>Payments and credits</CardTitle></CardHeader><CardContent className="space-y-3">{invoice.payments.map(entry => <div className="flex flex-wrap justify-between gap-3 rounded-lg border p-4" key={entry.id}><div><p className="font-medium capitalize">{entry.type} · {entry.method.replace('_', ' ')}</p><p className="text-xs text-gray-500">{new Date(entry.processedAt).toLocaleString()} {entry.reference ? `· ${entry.reference}` : ''}</p>{entry.notes && <p className="mt-1 text-sm text-gray-600">{entry.notes}</p>}</div><p className="font-semibold">{money(entry.amount)}</p></div>)}</CardContent></Card>}
        {mode && <div className="fixed inset-0 z-50 grid place-items-center bg-black/45 p-4 print:hidden"><Card className="w-full max-w-md"><CardHeader><CardTitle>{mode === 'payment' ? 'Record payment' : mode === 'credit' ? 'Apply credit note' : 'Void invoice'}</CardTitle></CardHeader><CardContent><form className="space-y-4" onSubmit={submit}>{mode !== 'void' && <><div className="space-y-2"><Label>Amount</Label><Input type="number" min="0.01" step="0.01" max={invoice.balance} value={mode === 'payment' ? payment.data.amount : credit.data.amount} onChange={e => mode === 'payment' ? payment.setData('amount', e.target.value) : credit.setData('amount', e.target.value)}/></div>{mode === 'payment' && <><div className="space-y-2"><Label>Method</Label><Select value={payment.data.method} onValueChange={value => payment.setData('method', value)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['cash','card','bank_transfer','external_terminal','provider','other'].map(value => <SelectItem key={value} value={value}>{value.replace('_', ' ')}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Reference</Label><Input value={payment.data.reference} onChange={e => payment.setData('reference', e.target.value)}/></div></>}{mode === 'credit' && <div className="space-y-2"><Label>Reason</Label><Textarea value={credit.data.notes} onChange={e => credit.setData('notes', e.target.value)} required minLength={5}/></div>}</>}{mode === 'void' && <div className="space-y-2"><Label>Reason</Label><Textarea value={voidForm.data.reason} onChange={e => voidForm.setData('reason', e.target.value)} required minLength={8}/></div>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={() => setMode(null)}>Cancel</Button><Button type="submit" variant={mode === 'void' ? 'destructive' : 'default'}>Confirm</Button></div></form></CardContent></Card></div>}
    </div></AdminLayout>;
}
