<?php
namespace App\Http\Controllers\Dashboard;
use App\Http\Controllers\Controller;use App\Models\{FoodCategory,FoodItem,FoodOrder,Folio,FolioItem};use App\Services\Folios\FolioLedger;use App\Services\Security\AuditLogger;use Illuminate\Http\{RedirectResponse,Request};use Illuminate\Validation\Rule;use Inertia\{Inertia,Response};
class FoodBeverageController extends Controller{
 public function index():Response{return Inertia::render('Dashboard/FoodBeverage/Index',['categories'=>FoodCategory::with(['items'=>fn($q)=>$q->orderBy('name')])->orderBy('sort_order')->get()->map(fn($c)=>['id'=>$c->id,'name'=>$c->name,'active'=>$c->active,'items'=>$c->items->map(fn($i)=>['id'=>$i->id,'name'=>$i->name,'description'=>$i->description,'price'=>(float)$i->price,'taxRate'=>(float)$i->tax_rate,'dietaryTags'=>$i->dietary_tags??[],'allergens'=>$i->allergens,'available'=>$i->available])]),'orders'=>FoodOrder::with(['items','guest','room'])->latest()->limit(150)->get()->map(fn($o)=>['id'=>$o->id,'number'=>$o->number,'status'=>$o->status,'guest'=>trim($o->guest->first_name.' '.$o->guest->last_name),'room'=>$o->room->number,'total'=>(float)$o->total,'notes'=>$o->notes,'createdAt'=>$o->created_at->toISOString(),'items'=>$o->items->map(fn($i)=>['name'=>$i->name,'quantity'=>$i->quantity,'modifiers'=>$i->modifiers])])]);}
 public function category(Request$r):RedirectResponse{$v=$r->validate(['name'=>'required|string|max:100']);$c=FoodCategory::create($v+['sort_order'=>FoodCategory::max('sort_order')+1]);AuditLogger::record($r,'food_category_created','food_beverage','normal',"Menu category {$c->name} created.",$c);return back()->with('success','Menu category created.');}
 public function item(Request$r):RedirectResponse{$v=$r->validate(['food_category_id'=>'required|exists:food_categories,id','name'=>'required|string|max:150','description'=>'nullable|string|max:1000','price'=>'required|numeric|min:0','tax_rate'=>'required|numeric|between:0,100','dietary_tags'=>'array','dietary_tags.*'=>'string|max:40','allergens'=>'nullable|string|max:500','available'=>'required|boolean']);$item=FoodItem::create($v);AuditLogger::record($r,'food_item_created','food_beverage','normal',"Menu item {$item->name} created.",$item);return back()->with('success','Menu item created.');}
 public function updateItem(Request$r,FoodItem$item):RedirectResponse{$v=$r->validate(['available'=>'required|boolean']);$item->update($v);return back()->with('success',$item->available?'Item is available.':'Item marked sold out.');}
 public function status(Request$r,FoodOrder$order,FolioLedger$ledger):RedirectResponse{$status=$r->validate(['status'=>['required',Rule::in(['accepted','preparing','ready','out_for_delivery','delivered','cancelled'])]])['status'];$allowed=['new'=>['accepted','cancelled'],'accepted'=>['preparing','cancelled'],'preparing'=>['ready','cancelled'],'ready'=>['out_for_delivery','delivered'],'out_for_delivery'=>['delivered']];abort_unless(in_array($status,$allowed[$order->status]??[],true),422,'That order status transition is not allowed.');$timestamps=match($status){'accepted'=>['accepted_at'=>now()],'ready'=>['ready_at'=>now()],'delivered'=>['delivered_at'=>now()],'cancelled'=>['cancelled_at'=>now()],default=>[]};$order->update(['status'=>$status,'updated_by'=>$r->user()->id,...$timestamps]);if($status==='delivered'&&$order->payment_method==='room_charge'&&$order->checkin?->reservation_id){$folio=Folio::forReservation($order->checkin->reservation);FolioItem::firstOrCreate(['idempotency_key'=>"food-order:{$order->id}"],['folio_id'=>$folio->id,'type'=>'service','description'=>"Room service {$order->number}",'quantity'=>1,'unit_amount'=>$order->subtotal,'tax_amount'=>$order->tax_total,'total_amount'=>$order->total,'service_date'=>today(),'posted_by'=>$r->user()->id,'metadata'=>['food_order_id'=>$order->id]]);$ledger->recalculate($folio);}AuditLogger::record($r,'food_order_status_changed','food_beverage','sensitive',"Order {$order->number} changed to {$status}.",$order);return back()->with('success','Order status updated.');}
}
