<?php
namespace App\Http\Controllers\Dashboard;
use App\Http\Controllers\Controller;use App\Models\{GuestRequestEvent,GuestRequestMessage,GuestServiceRequest};use App\Services\Notifications\MobileNotifier;use App\Services\Security\AuditLogger;use Illuminate\Http\{RedirectResponse,Request};use Illuminate\Support\Facades\Storage;
class GuestRequestController extends Controller{
 public function message(Request$request,GuestServiceRequest$serviceRequest,MobileNotifier$notifier):RedirectResponse{$this->authorizeStaff($request);$data=$request->validate(['message'=>'required|string|max:2000','internal'=>'required|boolean','attachment'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120']);$path=$request->file('attachment')?->store("guest-request-attachments/{$serviceRequest->id}",'local');$message=$serviceRequest->messages()->create(['user_id'=>$request->user()->id,'message'=>$data['message'],'internal'=>$data['internal'],'attachment_path'=>$path,'read_by_staff_at'=>now()]);GuestRequestEvent::create(['guest_service_request_id'=>$serviceRequest->id,'user_id'=>$request->user()->id,'event_type'=>$data['internal']?'internal_note':'staff_replied','label'=>$data['internal']?'Staff added an internal note.':$request->user()->name.' replied to the guest.','occurred_at'=>now()]);if(!$data['internal'])$notifier->send($serviceRequest->guest,'service','New message about your request',$data['message'],['type'=>'request_message','request_id'=>$serviceRequest->id]);AuditLogger::record($request,'guest_request_message','operations','standard',$data['internal']?'Internal request note added.':'Guest-visible request reply sent.',$serviceRequest);return back()->with('success',$data['internal']?'Internal note added.':'Reply sent to guest.');}
 public function complete(Request$request,GuestServiceRequest$serviceRequest,MobileNotifier$notifier):RedirectResponse{$this->authorizeStaff($request);$data=$request->validate(['completion_message'=>'required|string|max:2000','completion_photo'=>'nullable|image|mimes:jpg,jpeg,png,webp|max:5120']);$path=$request->file('completion_photo')?->store("guest-request-completions/{$serviceRequest->id}",'local');$serviceRequest->update(['status'=>'completed','completed_at'=>now(),'completion_photo'=>$path]);$serviceRequest->housekeepingTask?->update(['status'=>'completed','completed_at'=>now()]);$serviceRequest->maintenanceWorkOrder?->update(['status'=>'repaired','repaired_at'=>now(),'repair_notes'=>$data['completion_message']]);$serviceRequest->messages()->create(['user_id'=>$request->user()->id,'message'=>$data['completion_message'],'read_by_staff_at'=>now()]);GuestRequestEvent::create(['guest_service_request_id'=>$serviceRequest->id,'user_id'=>$request->user()->id,'event_type'=>'completed','label'=>'Staff marked the request completed.','occurred_at'=>now()]);$notifier->send($serviceRequest->guest,'service','Request completed',$data['completion_message'],['type'=>'request_completed','request_id'=>$serviceRequest->id]);return back()->with('success','Completion shared with the guest.');}
 public function read(Request$request,GuestServiceRequest$serviceRequest):RedirectResponse{$this->authorizeStaff($request);$serviceRequest->messages()->whereNotNull('guest_id')->whereNull('read_by_staff_at')->update(['read_by_staff_at'=>now()]);return back();}
 public function attachment(Request$request,GuestServiceRequest$serviceRequest,GuestRequestMessage$message){$this->authorizeStaff($request);abort_unless($message->guest_service_request_id===$serviceRequest->id&&$message->attachment_path&&Storage::disk('local')->exists($message->attachment_path),404);return Storage::disk('local')->response($message->attachment_path,null,['Cache-Control'=>'no-store, private']);}
 private function authorizeStaff(Request$request):void{abort_unless($request->user()->hasPermission('housekeeping')||$request->user()->hasPermission('maintenance'),403);}
}
