<?php
namespace App\Http\Controllers\Dashboard;
use App\Http\Controllers\Controller;use App\Models\{Checkin,HousekeepingTask,LockCommand,LockDevice,MaintenanceWorkOrder,Reservation,Room};use App\Services\Security\AuditLogger;use Carbon\Carbon;use Carbon\CarbonPeriod;use Illuminate\Http\Request;use Illuminate\Support\Collection;use Illuminate\Support\Facades\Response as Download;use Inertia\Inertia;use Inertia\Response;use Symfony\Component\HttpFoundation\StreamedResponse;
class ReportController extends Controller{
 public function index(Request$request):Response{$dates=$this->dates($request);return Inertia::render('Dashboard/Reports/Reports',$this->report($dates['from'],$dates['to'])+['filters'=>['from'=>$dates['from']->toDateString(),'to'=>$dates['to']->toDateString()]]);}
 public function export(Request$request):StreamedResponse{$dates=$this->dates($request);$report=$this->report($dates['from'],$dates['to']);AuditLogger::record($request,'reports_exported','reports','normal','Operational reports exported to CSV.',null,null,['from'=>$dates['from']->toDateString(),'to'=>$dates['to']->toDateString()]);return Download::streamDownload(function()use($report,$dates){$out=fopen('php://output','w');fputcsv($out,['HotelKey Operational Report',$dates['from']->toDateString().' to '.$dates['to']->toDateString()]);fputcsv($out,[]);fputcsv($out,['Metric','Value']);foreach($report['summary']as$key=>$value)fputcsv($out,[str($key)->replace('_',' ')->title(),$value]);fputcsv($out,[]);fputcsv($out,['Room','Stays','Occupied nights','Maintenance orders','Maintenance cost']);foreach($report['roomPerformance']as$row)fputcsv($out,[$row['roomNumber'],$row['stays'],$row['occupiedNights'],$row['maintenanceOrders'],$row['maintenanceCost']]);fputcsv($out,[]);fputcsv($out,['Housekeeper','Tasks','Average cleaning minutes']);foreach($report['housekeepingWorkers']as$row)fputcsv($out,[$row['name'],$row['tasks'],$row['averageMinutes']]);fclose($out);},'hotel-operations-'.$dates['from']->format('Ymd').'-'.$dates['to']->format('Ymd').'.csv',['Content-Type'=>'text/csv']);}
 private function dates(Request$request):array{$v=$request->validate(['from'=>['nullable','date'],'to'=>['nullable','date','after_or_equal:from']]);$from=Carbon::parse($v['from']??now()->subDays(29)->toDateString())->startOfDay();$to=Carbon::parse($v['to']??today()->toDateString())->endOfDay();abort_if($from->diffInDays($to)>366,422,'Reports are limited to a 367-day range.');return compact('from','to');}
 private function report(Carbon$from,Carbon$to):array{
  $rooms=Room::orderBy('number')->get();$checkins=Checkin::with('room')->whereDate('check_in_date','<=',$to)->where(fn($q)=>$q->whereNull('check_out_date')->orWhereDate('check_out_date','>=',$from))->get();$reservations=Reservation::whereDate('arrival_date','>=',$from->toDateString())->whereDate('arrival_date','<=',$to->toDateString())->get();$housekeeping=HousekeepingTask::with(['room','assignee'])->whereBetween('created_at',[$from,$to])->get();$maintenance=MaintenanceWorkOrder::with(['room','assignee'])->whereBetween('created_at',[$from,$to])->get();$commands=LockCommand::whereBetween('created_at',[$from,$to])->get();$days=$from->copy()->startOfDay()->diffInDays($to->copy()->startOfDay())+1;
  $occupiedNights=$checkins->sum(fn($stay)=>$this->overlapDays($stay->check_in_date,$stay->check_out_date??$to,$from,$to));$capacity=max(1,$rooms->count()*$days);$cleaningMinutes=$housekeeping->filter(fn($t)=>$t->started_at&&$t->completed_at)->map(fn($t)=>$t->started_at->diffInMinutes($t->completed_at));$repairMinutes=$maintenance->filter(fn($o)=>$o->started_at&&$o->repaired_at)->map(fn($o)=>$o->started_at->diffInMinutes($o->repaired_at));
  $trend=collect(CarbonPeriod::create($from->copy()->startOfDay(),$to->copy()->startOfDay()))->map(function($date)use($checkins,$reservations,$rooms){$occupied=$checkins->filter(fn($s)=>$s->check_in_date->lte($date)&&(!$s->check_out_date||$s->check_out_date->gte($date)))->pluck('room_id')->unique()->count();return['date'=>$date->format('M j'),'occupancy'=>$rooms->count()?round($occupied/$rooms->count()*100,1):0,'revenue'=>(float)$reservations->filter(fn($r)=>$r->arrival_date->isSameDay($date))->sum('amount_paid')];})->values();
  $roomPerformance=$rooms->map(function($room)use($checkins,$maintenance,$from,$to){$stays=$checkins->where('room_id',$room->id);$orders=$maintenance->where('room_id',$room->id);return['roomNumber'=>$room->number,'stays'=>$stays->count(),'occupiedNights'=>$stays->sum(fn($s)=>$this->overlapDays($s->check_in_date,$s->check_out_date??$to,$from,$to)),'maintenanceOrders'=>$orders->count(),'maintenanceCost'=>(float)$orders->sum('cost')];})->sortByDesc('occupiedNights')->values();
  $workers=$housekeeping->whereNotNull('assigned_to')->groupBy('assigned_to')->map(function(Collection$tasks){$durations=$tasks->filter(fn($t)=>$t->started_at&&$t->completed_at)->map(fn($t)=>$t->started_at->diffInMinutes($t->completed_at));return['name'=>$tasks->first()->assignee?->name??'Former staff','tasks'=>$tasks->count(),'averageMinutes'=>$durations->isNotEmpty()?round($durations->avg(),1):null];})->values();
  $categories=$maintenance->groupBy('category')->map(fn($items,$name)=>['name'=>str($name)->title()->toString(),'count'=>$items->count(),'cost'=>(float)$items->sum('cost')])->sortByDesc('count')->values();$lockDevices=LockDevice::all();
  return['summary'=>['occupancy_rate'=>round($occupiedNights/$capacity*100,1),'occupied_nights'=>$occupiedNights,'collected_revenue'=>(float)$reservations->sum('amount_paid'),'outstanding_balance'=>(float)$reservations->sum(fn($r)=>max(0,(float)$r->total_amount-(float)$r->amount_paid)),'reservations'=>$reservations->count(),'average_cleaning_minutes'=>$cleaningMinutes->isNotEmpty()?round($cleaningMinutes->avg(),1):null,'average_repair_minutes'=>$repairMinutes->isNotEmpty()?round($repairMinutes->avg(),1):null,'maintenance_cost'=>(float)$maintenance->sum('cost')],'trend'=>$trend,'housekeeping'=>['total'=>$housekeeping->count(),'completed'=>$housekeeping->whereIn('status',['completed','inspected'])->count(),'overdue'=>$housekeeping->filter(fn($t)=>$t->due_at?->isPast()&&!in_array($t->status,['inspected']))->count()],'maintenance'=>['total'=>$maintenance->count(),'repaired'=>$maintenance->whereIn('status',['repaired','inspected'])->count(),'overdue'=>$maintenance->filter(fn($o)=>$o->due_at?->isPast()&&!in_array($o->status,['inspected','cancelled']))->count()],'locks'=>['total'=>$lockDevices->count(),'offline'=>$lockDevices->where('status','!=','online')->count(),'lowBattery'=>$lockDevices->where('battery_level','<',25)->count(),'failedCommands'=>$commands->where('status','failed')->count()],'roomPerformance'=>$roomPerformance,'housekeepingWorkers'=>$workers,'maintenanceCategories'=>$categories];
 }
 private function overlapDays($start,$end,Carbon$from,Carbon$to):int{$start=Carbon::parse($start)->max($from->copy()->startOfDay());$end=Carbon::parse($end)->min($to->copy()->startOfDay());return max(1,$start->diffInDays($end));}
}
