import { FormEvent, ReactNode, useState } from 'react';
import { Head, Link, router, useForm } from '@inertiajs/react';
import { AdminLayout } from '@/components/layout/AdminLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { ArrowLeft, ArrowRight, CalendarDays, Hotel, Plus, SlidersHorizontal, Users } from 'lucide-react';

type Room = { id:number; number:string; type:string; status:string; price:number };
type Reservation = { id:number; reference:string; guestName:string; roomId:number|null; roomNumber:string|null; roomType:string|null; arrivalDate:string; departureDate:string; status:string; groupCode:string|null };
type Block = { id:number; roomId:number|null; roomNumber:string|null; roomType:string|null; name:string; groupCode:string|null; startDate:string; endDate:string; quantity:number };
type Rule = { id:number; roomType:string; startDate:string; endDate:string; nightlyRate:number|null; minimumStay:number; closedToArrival:boolean };
type Props = { view:'week'|'month'; start:string; end:string; dates:string[]; rooms:Room[]; reservations:Reservation[]; unassigned:Reservation[]; blocks:Block[]; rules:Rule[]; roomTypes:string[]; availability:Record<string,Record<string,number>>; stats:{arrivals:number;departures:number;stayOvers:number;unassigned:number} };

export default function Planner(p: Props) {
 const [blockOpen,setBlockOpen]=useState(false), [ruleOpen,setRuleOpen]=useState(false), [dragging,setDragging]=useState<number|null>(null);
 const navigate=(start:string,view=p.view)=>router.get(route('dashboard.bookings.planner'),{start,view},{preserveState:true});
 const shift=(n:number)=>{const d=new Date(`${p.start}T12:00:00`);d.setDate(d.getDate()+n);navigate(d.toISOString().slice(0,10))};
 const drop=(roomId:number,date:string)=>{if(dragging)router.patch(route('dashboard.bookings.move',dragging),{room_id:roomId,arrival_date:date},{preserveScroll:true});setDragging(null)};
 return <AdminLayout title="Reservation planner"><Head title="Reservation planner"/><div className="space-y-6">
  <header className="flex flex-wrap items-start justify-between gap-4"><div><Link href={route('dashboard.bookings')} className="text-sm font-medium text-indigo-600">← Reservation list</Link><h1 className="mt-2 text-2xl font-bold">Reservation planner</h1><p className="text-gray-600">Assign rooms and protect availability from conflicts.</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>setRuleOpen(true)}><SlidersHorizontal className="mr-2" size={16}/>Rates &amp; rules</Button><Button onClick={()=>setBlockOpen(true)}><Plus className="mr-2" size={16}/>Block inventory</Button></div></header>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<CalendarDays/>} label="Arrivals" value={p.stats.arrivals}/><Stat icon={<ArrowRight/>} label="Departures" value={p.stats.departures}/><Stat icon={<Hotel/>} label="Stay-overs" value={p.stats.stayOvers}/><Stat icon={<Users/>} label="Unassigned" value={p.stats.unassigned} warning={p.stats.unassigned>0}/></div>
  {p.unassigned.length>0&&<section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-semibold text-amber-950">Unassigned reservations</h2><p className="mb-3 text-sm text-amber-800">Drag a booking onto an available room and arrival date.</p><div className="flex flex-wrap gap-2">{p.unassigned.map(r=><Booking key={r.id} r={r} drag={setDragging} rangeStart={p.start} rangeEnd={p.end}/>)}</div></section>}
  <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={()=>shift(p.view==='month'?-28:-7)}><ArrowLeft size={16}/></Button><Button size="sm" variant="outline" onClick={()=>navigate(new Date().toISOString().slice(0,10))}>Today</Button><Button size="sm" variant="outline" onClick={()=>shift(p.view==='month'?28:7)}><ArrowRight size={16}/></Button><strong className="ml-2 text-sm">{date(p.start)} – {date(p.end)}</strong></div><div className="flex rounded-lg bg-gray-100 p-1"><View active={p.view==='week'} onClick={()=>navigate(p.start,'week')}>Week</View><View active={p.view==='month'} onClick={()=>navigate(p.start,'month')}>4 weeks</View></div></div>
   <div className="overflow-x-auto"><div style={{minWidth:170+p.dates.length*112}}><Row dates={p.dates}/>{p.rooms.map(room=><div key={room.id} className="grid min-h-[82px] border-b" style={{gridTemplateColumns:`170px repeat(${p.dates.length},minmax(112px,1fr))`}}><div className="sticky left-0 z-20 border-r bg-white p-3"><strong>Room {room.number}</strong><div className="text-xs text-gray-500">{room.type} · ${room.price}</div><span className={`mt-1 inline-block rounded-full px-2 py-0.5 text-[10px] ${room.status==='available'?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700'}`}>{room.status.replaceAll('_',' ')}</span></div>{p.dates.map(d=><div key={d} onDragOver={e=>e.preventDefault()} onDrop={()=>drop(room.id,d)} className={`relative border-r p-1 ${dragging?'hover:bg-indigo-100':''} ${today(d)?'bg-indigo-50/50':''}`}><div className="text-center text-[10px] text-gray-400">{p.availability[room.type]?.[d]??0} left</div>{p.reservations.filter(r=>r.roomId===room.id&&(r.arrivalDate<p.start?p.start:r.arrivalDate)===d).map(r=><Booking key={r.id} r={r} drag={setDragging} rangeStart={p.start} rangeEnd={p.end}/>)}{p.blocks.filter(b=>b.roomId===room.id&&(b.startDate<p.start?p.start:b.startDate)===d).map(b=><div key={b.id} className="mt-1 rounded-md bg-slate-200 p-2 text-xs"><strong>{b.name}</strong><button className="block text-[10px] text-red-600" onClick={()=>router.patch(route('dashboard.inventory-blocks.release',b.id))}>Release</button></div>)}</div>)}</div>)}</div></div>
  </section>
  <section className="rounded-xl border bg-white p-5 shadow-sm"><h2 className="font-semibold">Room-type availability</h2><p className="mb-4 text-sm text-gray-500">Remaining sellable inventory after bookings and type-level holds.</p><div className="overflow-x-auto"><table className="min-w-full text-sm"><thead><tr><th className="p-2 text-left">Type</th>{p.dates.map(d=><th key={d} className="p-2 text-center">{shortDate(d)}</th>)}</tr></thead><tbody>{p.roomTypes.map(t=><tr key={t} className="border-t"><th className="p-2 text-left">{t}</th>{p.dates.map(d=>{const n=p.availability[t]?.[d]??0;return <td key={d} className={`p-2 text-center font-medium ${n===0?'bg-red-50 text-red-700':n===1?'bg-amber-50 text-amber-700':'text-emerald-700'}`}>{n}</td>})}</tr>)}</tbody></table></div></section>
 </div>{blockOpen&&<BlockModal {...p} close={()=>setBlockOpen(false)}/>} {ruleOpen&&<RuleModal {...p} close={()=>setRuleOpen(false)}/>}</AdminLayout>;
}

function Row({dates}:{dates:string[]}){return <div className="grid border-b bg-gray-50" style={{gridTemplateColumns:`170px repeat(${dates.length},minmax(112px,1fr))`}}><div className="sticky left-0 z-20 border-r bg-gray-50 p-3 text-xs font-semibold uppercase text-gray-500">Room</div>{dates.map(d=><div key={d} className={`border-r p-3 text-center ${today(d)?'bg-indigo-50 text-indigo-700':''}`}><div className="text-xs uppercase">{new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{weekday:'short'})}</div><strong>{new Date(`${d}T12:00:00`).getDate()}</strong></div>)}</div>}
function Booking({r,drag,rangeStart,rangeEnd}:{r:Reservation;drag:(id:number|null)=>void;rangeStart:string;rangeEnd:string}){const days=r.roomId?span(r.arrivalDate,r.departureDate,rangeStart,rangeEnd):1;return <div draggable onDragStart={()=>drag(r.id)} onDragEnd={()=>drag(null)} title={`${r.guestName}: ${r.arrivalDate}–${r.departureDate}`} style={r.roomId?{width:`calc(${days * 100}% + ${(days-1)*4}px)`}:undefined} className="relative z-10 mt-1 cursor-grab rounded-md border border-indigo-200 bg-indigo-100 p-2 text-xs text-indigo-950 shadow-sm"><strong className="block truncate">{r.guestName}</strong><span className="block truncate text-[10px] text-indigo-700">{r.reference}{r.groupCode?` · ${r.groupCode}`:''}</span></div>}
function Stat({icon,label,value,warning}:{icon:ReactNode;label:string;value:number;warning?:boolean}){return <div className={`flex items-center gap-4 rounded-xl border bg-white p-4 shadow-sm ${warning?'border-amber-300':''}`}><div className={`rounded-lg p-2 ${warning?'bg-amber-100 text-amber-700':'bg-indigo-50 text-indigo-600'}`}>{icon}</div><div><p className="text-sm text-gray-500">{label}</p><p className="text-2xl font-bold">{value}</p></div></div>}
function View({active,onClick,children}:{active:boolean;onClick:()=>void;children:ReactNode}){return <button className={`rounded-md px-3 py-1.5 text-sm ${active?'bg-white font-medium shadow-sm':'text-gray-600'}`} onClick={onClick}>{children}</button>}
function BlockModal(p:Props&{close:()=>void}){const f=useForm({room_id:'',room_type:'',name:'',group_code:'',start_date:p.start,end_date:'',quantity:'1',notes:''});const submit=(e:FormEvent)=>{e.preventDefault();f.post(route('dashboard.inventory-blocks.store'),{onSuccess:p.close})};return <Modal close={p.close}><form onSubmit={submit}><h2 className="text-xl font-semibold">Block inventory</h2><p className="text-sm text-gray-500">Hold a room or room-type quantity for maintenance, owners, or groups.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Name"><Input required value={f.data.name} onChange={e=>f.setData('name',e.target.value)}/></Field><Field label="Group code"><Input value={f.data.group_code} onChange={e=>f.setData('group_code',e.target.value)}/></Field><Field label="Specific room"><select className="w-full rounded-md border p-2" value={f.data.room_id} onChange={e=>{f.setData('room_id',e.target.value);if(e.target.value)f.setData('room_type','')}}><option value="">None</option>{p.rooms.map(r=><option key={r.id} value={r.id}>Room {r.number} · {r.type}</option>)}</select></Field><Field label="Or room type"><select className="w-full rounded-md border p-2" value={f.data.room_type} onChange={e=>{f.setData('room_type',e.target.value);if(e.target.value)f.setData('room_id','')}}><option value="">Select</option>{p.roomTypes.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Start"><Input type="date" required value={f.data.start_date} onChange={e=>f.setData('start_date',e.target.value)}/></Field><Field label="End"><Input type="date" required value={f.data.end_date} onChange={e=>f.setData('end_date',e.target.value)}/></Field><Field label="Quantity"><Input type="number" min="1" required value={f.data.quantity} onChange={e=>f.setData('quantity',e.target.value)}/></Field></div><Actions close={p.close} busy={f.processing} label="Create block"/></form></Modal>}
function RuleModal(p:Props&{close:()=>void}){const f=useForm({room_type:p.roomTypes[0]??'',start_date:p.start,end_date:p.end,nightly_rate:'',minimum_stay:'1',closed_to_arrival:false as boolean,notes:''});const submit=(e:FormEvent)=>{e.preventDefault();f.post(route('dashboard.room-rate-rules.store'))};return <Modal close={p.close}><h2 className="text-xl font-semibold">Rates &amp; stay rules</h2><form onSubmit={submit} className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Room type"><select required className="w-full rounded-md border p-2" value={f.data.room_type} onChange={e=>f.setData('room_type',e.target.value)}>{p.roomTypes.map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Nightly rate"><Input type="number" min="0" step=".01" value={f.data.nightly_rate} onChange={e=>f.setData('nightly_rate',e.target.value)} placeholder="Keep base rate"/></Field><Field label="Start"><Input type="date" required value={f.data.start_date} onChange={e=>f.setData('start_date',e.target.value)}/></Field><Field label="End"><Input type="date" required value={f.data.end_date} onChange={e=>f.setData('end_date',e.target.value)}/></Field><Field label="Minimum nights"><Input type="number" min="1" required value={f.data.minimum_stay} onChange={e=>f.setData('minimum_stay',e.target.value)}/></Field><label className="flex items-center gap-2 self-end rounded-md border p-2.5 text-sm"><input type="checkbox" checked={f.data.closed_to_arrival} onChange={e=>f.setData('closed_to_arrival',e.target.checked)}/>Closed to arrival</label><Button disabled={f.processing}>Add rule</Button></form><div className="mt-6 space-y-2 border-t pt-5">{p.rules.map(r=><div key={r.id} className="flex items-center justify-between rounded-lg bg-gray-50 p-3 text-sm"><div><strong>{r.roomType}</strong> · {shortDate(r.startDate)}–{shortDate(r.endDate)}<div className="text-xs text-gray-500">{r.nightlyRate!==null?`$${r.nightlyRate}/night · `:''}{r.minimumStay} night minimum{r.closedToArrival?' · Closed to arrival':''}</div></div><Button size="sm" variant="outline" onClick={()=>router.delete(route('dashboard.room-rate-rules.destroy',r.id))}>Remove</Button></div>)}{!p.rules.length&&<p className="text-sm text-gray-500">No special rules in this period.</p>}</div><div className="mt-5 flex justify-end"><Button variant="outline" onClick={p.close}>Close</Button></div></Modal>}
function Modal({children,close}:{children:ReactNode;close:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" onMouseDown={close}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl" onMouseDown={e=>e.stopPropagation()}>{children}</div></div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="space-y-1 text-sm font-medium"><span>{label}</span>{children}</label>}
function Actions({close,busy,label}:{close:()=>void;busy:boolean;label:string}){return <div className="mt-6 flex justify-end gap-2 border-t pt-5"><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={busy}>{label}</Button></div>}
const span=(start:string,end:string,rangeStart:string,rangeEnd:string)=>{const a=new Date(`${start<rangeStart?rangeStart:start}T12:00:00`),limit=end>rangeEnd?new Date(`${rangeEnd}T12:00:00`):new Date(`${end}T12:00:00`);return Math.max(1,Math.ceil((limit.getTime()-a.getTime())/86400000))};const date=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});const shortDate=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric'});const today=(d:string)=>d===new Date().toISOString().slice(0,10);
